/*
 * Felis
 *
 * The Felis Cloud API lets you execute quantum circuits on emulators and real quantum hardware made by Alice & Bob.  To run a circuit with the API: - Create a job with \"Create Job\", targeting a specific backend (listed by  \"List Targets\"). - Upload the input quantum code of your job in [QIR format](https://github.com/qir-alliance/qir-spec) with \"Upload Input\". - Monitor the job's status with \"Get Job\". - Read the results with \"Download Output\".  The execution stack includes a transpilation step to adapt the input code to the target's gate set. The result of the transpilation can be seen with \"Download Transpiled\".  This API is used by [Alice & Bob's Qiskit provider](https://github.com/Alice-Bob-SW/qiskit-alice-bob-provider), which also serves as a reference implementation.  Using this API requires an API key in the authorization header. Please reach out to Alice & Bob athttps://alice-bob.com/products/quantum-cloud-felis to learn how to get one.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TargetConfiguration {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "numQubits")]
    pub num_qubits: i32,
    #[serde(rename = "instructions")]
    pub instructions: Vec<models::Instruction>,
    #[serde(rename = "inputParams")]
    pub input_params: std::collections::HashMap<String, models::InputParamConfiguration>,
}

impl TargetConfiguration {
    pub fn new(name: String, num_qubits: i32, instructions: Vec<models::Instruction>, input_params: std::collections::HashMap<String, models::InputParamConfiguration>) -> TargetConfiguration {
        TargetConfiguration {
            name,
            num_qubits,
            instructions,
            input_params,
        }
    }
}

