//
// (C) Copyright IBM 2024, 2025
//
// This code is licensed under the Apache License, Version 2.0. You may
// obtain a copy of this license in the LICENSE.txt file in the root directory
// of this source tree or at http://www.apache.org/licenses/LICENSE-2.0.
//
// Any modifications or derivative works of this code must retain this
// copyright notice, and modified files need to carry a notice indicating
// that they have been altered from the originals.

//! # direct_access_client
//!
//! This is a Rust client to interact with IBM Quantum backend using the Direct Access API.
//!
//! The Direct Access API provides easy integrations of client’s on-premise IBM Quantum backend
//! and their scheduler/workflow.
//!
//! # Authentication
//! - [`API authentication`](crate::ClientBuilder::with_auth) by
//!   - a short lived access token generated by IBM Cloud Identity and Access Management (IAM) or
//!   - a short lived access token generated by IBM Cloud App ID or
//!   - internal shared key by passing client ID and its shared token
//! # Backend
//! - [`Get list of backends`](crate::Client::list_backends)
//! - [`Get backend details`](crate::Client::get_backend)
//! - [`Get backend configuration`](crate::Client::get_backend_configuration)
//! - [`Get backend properties`](crate::Client::get_backend_properties)
//! # Job
//! - [`Get jobs`](crate::Client::list_jobs)
//! - [`Get job by ID`](crate::Client::get_job)
//! - [`Run a job`](crate::Client::run_job)
//! - [`Deletes a job`](crate::Client::delete_job)
//! - [`Cancels a job`](crate::Client::cancel_job)
//! # Version
//! - [`Version`](crate::Client::get_service_version)
//!

mod api;
mod client;
#[allow(dead_code)]
#[allow(unused_imports)]
mod middleware;
pub mod models;
mod storages;
pub mod utils;

pub use client::{AuthMethod, Client, ClientBuilder, PrimitiveJob};
