/*  This code is part of Qiskit.
 *
 * (C) Copyright IBM 2026
 *
 * This code is licensed under the Apache License, Version 2.0. You may
 * obtain a copy of this license in the LICENSE.txt file in the root directory
 * of this source tree or at http://www.apache.org/licenses/LICENSE-2.0.
 *
 * Any modifications or derivative works of this code must retain this
 * copyright notice, and modified files need to carry a notice indicating
 * that they have been altered from the originals.
 */

/**
 * @file lua_qrmi.c
 * @brief Lua binding for the real QRMI C API (qrmi.h, generated by cbindgen).
 *
 * Main differences from the earlier mock version:
 *   1. Every call now returns a QrmiReturnCode (out-parameter style)
 *   2. The resource just holds an opaque pointer (QrmiQuantumResource*)
 *   3. Any string allocated on the Rust side must be freed with qrmi_string_free()
 *   4. task_start builds a tagged union called QrmiPayload to pass in
 *   5. On error, qrmi_get_last_error() is called to get a detailed message
 */
#include <lua.h>
#include <lauxlib.h>
#include <lualib.h>
#include <string.h>
#include "qrmi.h"

/** @brief Metatable name used to identify `qrmi.resource` userdata. */
#define QRMI_RESOURCE_MT "qrmi.resource"

/** @brief Metatable name used to identify `qrmi.config` userdata. */
#define QRMI_CONFIG_MT "qrmi.config"

/**
 * @brief Lua userdata payload backing a `qrmi.resource` object.
 */
typedef struct {
    QrmiQuantumResource *handle;      /**< NULL once freed. */
    char *acquisition_token;          /**< Non-NULL once acquired; kept so __gc can auto-release. */
} lua_qrmi_resource_t;

/**
 * @brief Lua userdata payload backing a `qrmi.config` object.
 *
 * Entirely independent from `lua_qrmi_resource_t` / `qrmi.resource`: this
 * wraps QrmiConfig (loaded from a qrmi_config.json file), which has its own
 * separate lifecycle unrelated to any QrmiQuantumResource handle.
 */
typedef struct {
    QrmiConfig *handle;                /**< NULL once freed. */
} lua_qrmi_config_t;

/* --- shared helpers ----------------------------------------------------- */

/**
 * @brief Push a Lua-style (nil, errmsg) error pair for a failed QrmiReturnCode.
 *
 * Fetches the thread-local detail message via qrmi_get_last_error() when
 * available, otherwise falls back to a generic message containing the
 * numeric return code.
 *
 * @param L  Lua state to push onto.
 * @param rc The failing QrmiReturnCode returned by the QRMI C API call.
 * @return Always 2 (number of values pushed: nil, errmsg).
 */
static int push_qrmi_error(lua_State *L, QrmiReturnCode rc) {
    const char *err = qrmi_get_last_error();
    lua_pushnil(L);
    if (err) {
        lua_pushstring(L, err);
    } else {
        lua_pushfstring(L, "qrmi error (code=%d)", (int)rc);
    }
    return 2;
}

/** @brief All QrmiResourceType variants, used to drive the string <-> enum lookup below. */
static const QrmiResourceType g_all_resource_types[] = {
    QRMI_RESOURCE_TYPE_IBM_QUANTUM_SYSTEM,
    QRMI_RESOURCE_TYPE_QISKIT_RUNTIME_SERVICE,
    QRMI_RESOURCE_TYPE_PASQAL_CLOUD,
    QRMI_RESOURCE_TYPE_PASQAL_LOCAL,
    QRMI_RESOURCE_TYPE_ALICE_BOB_FELIS,
    QRMI_RESOURCE_TYPE_IQM_SERVER,
};

/**
 * @brief Convert a Lua-facing resource type string to a QrmiResourceType.
 *
 * Rather than hardcoding a string table, this matches against the
 * canonical names returned by qrmi_config_resource_type_to_str() (e.g.
 * "qiskit-runtime-service", hyphen-separated, matching qrmi_config.json's
 * convention), so the accepted spelling always tracks the real library.
 *
 * @param s Resource type name, e.g. "ibm-quantum-system".
 * @param[out] out Set to the matching QrmiResourceType on success.
 *                 Left untouched on failure.
 * @return QRMI_RETURN_CODE_SUCCESS if @p s was recognized,
 *         QRMI_RETURN_CODE_ERROR otherwise.
 */
static QrmiReturnCode resource_type_from_string(const char *s, QrmiResourceType *out) {
    size_t n = sizeof(g_all_resource_types) / sizeof(g_all_resource_types[0]);
    for (size_t i = 0; i < n; i++) {
        const char *name = qrmi_config_resource_type_to_str(g_all_resource_types[i]);
        if (name && strcmp(name, s) == 0) {
            *out = g_all_resource_types[i];
            return QRMI_RETURN_CODE_SUCCESS;
        }
    }
    return QRMI_RETURN_CODE_ERROR;
}

/**
 * @brief Convert a QrmiTaskStatus enum value to its Lua-facing string form.
 *
 * @param s A QrmiTaskStatus value as returned by qrmi_resource_task_status().
 * @return One of "queued", "running", "completed", "failed", "cancelled",
 *         or "unknown" if @p s does not match any known variant.
 */
static const char *task_status_to_string(QrmiTaskStatus s) {
    switch (s) {
        case QRMI_TASK_STATUS_QUEUED:    return "queued";
        case QRMI_TASK_STATUS_RUNNING:   return "running";
        case QRMI_TASK_STATUS_COMPLETED: return "completed";
        case QRMI_TASK_STATUS_FAILED:    return "failed";
        case QRMI_TASK_STATUS_CANCELLED: return "cancelled";
        default: return "unknown";
    }
}

/**
 * @brief `qrmi.new(resource_id, resource_type_str)` - Create a quantum resource handle.
 *
 * Wraps qrmi_resource_new().
 *
 * Lua usage:
 * @code
 *   local resource, err = qrmi.new("ibm_kingston", "ibm_quantum_system")
 * @endcode
 *
 * @param L Lua state. Stack arguments:
 *   - [1] resource_id (string)   e.g. "ibm_kingston"
 *   - [2] resource_type (string) canonical hyphenated name as returned by
 *         qrmi_config_resource_type_to_str(), e.g. "ibm-quantum-system",
 *         "qiskit-runtime-service", "pasqal-cloud", "pasqal-local",
 *         "alice-bob-felis", "iqm-server"
 * @return Number of values pushed onto the Lua stack.
 *         On success: 1 (resource: qrmi.resource userdata)
 *         On failure: 2 (nil, err: string)
 */
static int l_qrmi_new(lua_State *L) {
    const char *resource_id = luaL_checkstring(L, 1);
    const char *type_str = luaL_checkstring(L, 2);

    QrmiResourceType type;
    QrmiReturnCode type_rc = resource_type_from_string(type_str, &type);
    if (type_rc != QRMI_RETURN_CODE_SUCCESS) {
        lua_pushnil(L);
        lua_pushfstring(L, "unknown resource type '%s'", type_str);
        return 2;
    }

    QrmiQuantumResource *handle = qrmi_resource_new(resource_id, type);
    if (!handle) {
        const char *err = qrmi_get_last_error();
        lua_pushnil(L);
        lua_pushstring(L, err ? err : "qrmi_resource_new failed");
        return 2;
    }

    lua_qrmi_resource_t *ud = (lua_qrmi_resource_t *)lua_newuserdata(L, sizeof(lua_qrmi_resource_t));
    ud->handle = handle;
    ud->acquisition_token = NULL;
    luaL_getmetatable(L, QRMI_RESOURCE_MT);
    lua_setmetatable(L, -2);
    return 1;
}

/**
 * @brief Fetch the lua_qrmi_resource_t backing a `qrmi.resource` userdata.
 *
 * Raises a Lua error (via luaL_error) if the resource has already been freed.
 *
 * @param L   Lua state.
 * @param idx Stack index of the `qrmi.resource` userdata argument.
 * @return Pointer to the resource's userdata payload. Never returns NULL
 *         (raises a Lua error instead, which does not return control here).
 */
static lua_qrmi_resource_t *check_resource(lua_State *L, int idx) {
    lua_qrmi_resource_t *ud = (lua_qrmi_resource_t *)luaL_checkudata(L, idx, QRMI_RESOURCE_MT);
    if (ud->handle == NULL) {
        luaL_error(L, "qrmi resource already freed");
    }
    return ud;
}

/**
 * @brief `resource:is_accessible()` - Check whether the device is reachable.
 *
 * Wraps qrmi_resource_is_accessible().
 *
 * Lua usage:
 * @code
 *   local accessible, err = resource:is_accessible()
 * @endcode
 *
 * @param L Lua state. Stack arguments: [1] resource (qrmi.resource userdata).
 * @return Number of values pushed onto the Lua stack.
 *         On success: 1 (accessible: boolean)
 *         On failure: 2 (nil, err: string)
 */
static int l_is_accessible(lua_State *L) {
    lua_qrmi_resource_t *ud = check_resource(L, 1);
    bool accessible = false;
    QrmiReturnCode rc = qrmi_resource_is_accessible(ud->handle, &accessible);
    if (rc != QRMI_RETURN_CODE_SUCCESS) return push_qrmi_error(L, rc);
    lua_pushboolean(L, accessible);
    return 1;
}

/**
 * @brief `resource:acquire()` - Acquire exclusive access to the quantum resource.
 *
 * Wraps qrmi_resource_acquire(). The returned token is also cached on the
 * userdata so that a later `resource:release()` call (with no arguments)
 * and the `__gc` finalizer can release it automatically.
 *
 * Lua usage:
 * @code
 *   local token, err = resource:acquire()
 * @endcode
 *
 * @param L Lua state. Stack arguments: [1] resource (qrmi.resource userdata).
 * @return Number of values pushed onto the Lua stack.
 *         On success: 1 (token: string)
 *         On failure: 2 (nil, err: string)
 */
static int l_acquire(lua_State *L) {
    lua_qrmi_resource_t *ud = check_resource(L, 1);
    char *token = NULL;
    QrmiReturnCode rc = qrmi_resource_acquire(ud->handle, &token);
    if (rc != QRMI_RETURN_CODE_SUCCESS) return push_qrmi_error(L, rc);

    if (ud->acquisition_token) free(ud->acquisition_token); /* just in case */
    ud->acquisition_token = strdup(token);

    lua_pushstring(L, token);
    qrmi_string_free(token);
    return 1;
}

/**
 * @brief `resource:release([token])` - Release a previously acquired resource.
 *
 * Wraps qrmi_resource_release(). If @p token is omitted, the token cached
 * by a prior `resource:acquire()` call is used instead.
 *
 * Lua usage:
 * @code
 *   local ok, err = resource:release()        -- uses cached token
 *   local ok, err = resource:release(token)   -- explicit token
 * @endcode
 *
 * @param L Lua state. Stack arguments:
 *   - [1] resource (qrmi.resource userdata)
 *   - [2] token (string, optional) acquisition token from `resource:acquire()`
 * @return Number of values pushed onto the Lua stack.
 *         On success: 1 (ok: boolean, always true)
 *         On failure: 2 (nil, err: string)
 */
static int l_release(lua_State *L) {
    lua_qrmi_resource_t *ud = check_resource(L, 1);
    const char *token = luaL_optstring(L, 2, ud->acquisition_token);
    if (!token) {
        lua_pushnil(L);
        lua_pushstring(L, "no acquisition token to release");
        return 2;
    }
    QrmiReturnCode rc = qrmi_resource_release(ud->handle, token);
    if (rc != QRMI_RETURN_CODE_SUCCESS) return push_qrmi_error(L, rc);

    if (ud->acquisition_token) {
        free(ud->acquisition_token);
        ud->acquisition_token = NULL;
    }
    lua_pushboolean(L, 1);
    return 1;
}

/**
 * @brief `resource:task_start(payload)` - Start a task.
 *
 * Wraps qrmi_resource_task_start(). Mirrors the C API's QrmiPayload tagged
 * union as a Lua table: the table's single key names the payload variant,
 * and its value is a sub-table holding that variant's fields. Only the
 * Qiskit Primitive variant is currently supported:
 *
 * @code
 *   payload = { qiskit_primitive = { program_id = "estimator", input = json_str } }
 * @endcode
 *
 * Pasqal/AliceBob/IQM payloads can be added later following the same
 * pattern, using a different top-level key (e.g. "pasqal_cloud") mapped
 * to the corresponding QrmiPayload_Tag and union member.
 *
 * Lua usage:
 * @code
 *   local task_id, err = resource:task_start({
 *       qiskit_primitive = {
 *           program_id = "estimator",
 *           input = '{"circuits": ["bell_state"]}',
 *       }
 *   })
 * @endcode
 *
 * @param L Lua state. Stack arguments:
 *   - [1] resource (qrmi.resource userdata)
 *   - [2] payload (table) as described above
 * @return Number of values pushed onto the Lua stack.
 *         On success: 1 (task_id: string)
 *         On failure: 2 (nil, err: string)
 */
static int l_task_start(lua_State *L) {
    lua_qrmi_resource_t *ud = check_resource(L, 1);
    luaL_checktype(L, 2, LUA_TTABLE);

    lua_getfield(L, 2, "qiskit_primitive");
    if (!lua_istable(L, -1)) {
        lua_pop(L, 1);
        lua_pushnil(L);
        lua_pushstring(L,
            "task_start: payload table must contain a 'qiskit_primitive' "
            "sub-table (other payload types not yet supported)");
        return 2;
    }
    int qp_idx = lua_gettop(L);

    lua_getfield(L, qp_idx, "input");
    const char *input = luaL_checkstring(L, -1);
    lua_getfield(L, qp_idx, "program_id");
    const char *program_id = luaL_checkstring(L, -1);

    QrmiPayload payload;
    payload.tag = QRMI_PAYLOAD_QISKIT_PRIMITIVE;
    payload.QISKIT_PRIMITIVE.input = (char *)input;
    payload.QISKIT_PRIMITIVE.program_id = (char *)program_id;

    char *task_id = NULL;
    QrmiReturnCode rc = qrmi_resource_task_start(ud->handle, &payload, &task_id);

    lua_settop(L, qp_idx - 1); /* drop qp_table, input, program_id */

    if (rc != QRMI_RETURN_CODE_SUCCESS) return push_qrmi_error(L, rc);

    lua_pushstring(L, task_id);
    qrmi_string_free(task_id);
    return 1;
}

/**
 * @brief `resource:task_status(task_id)` - Query a task's current status.
 *
 * Wraps qrmi_resource_task_status().
 *
 * Lua usage:
 * @code
 *   local status, err = resource:task_status(task_id)
 * @endcode
 *
 * @param L Lua state. Stack arguments:
 *   - [1] resource (qrmi.resource userdata)
 *   - [2] task_id (string) identifier returned by `resource:task_start()`
 * @return Number of values pushed onto the Lua stack.
 *         On success: 1 (status: string, one of "queued"/"running"/
 *         "completed"/"failed"/"cancelled")
 *         On failure: 2 (nil, err: string)
 */
static int l_task_status(lua_State *L) {
    lua_qrmi_resource_t *ud = check_resource(L, 1);
    const char *task_id = luaL_checkstring(L, 2);

    QrmiTaskStatus status;
    QrmiReturnCode rc = qrmi_resource_task_status(ud->handle, task_id, &status);
    if (rc != QRMI_RETURN_CODE_SUCCESS) return push_qrmi_error(L, rc);

    lua_pushstring(L, task_status_to_string(status));
    return 1;
}

/**
 * @brief `resource:task_result(task_id)` - Fetch a completed task's result.
 *
 * Wraps qrmi_resource_task_result().
 *
 * Lua usage:
 * @code
 *   local result_json, err = resource:task_result(task_id)
 * @endcode
 *
 * @param L Lua state. Stack arguments:
 *   - [1] resource (qrmi.resource userdata)
 *   - [2] task_id (string) identifier returned by `resource:task_start()`
 * @return Number of values pushed onto the Lua stack.
 *         On success: 1 (result_json: string)
 *         On failure: 2 (nil, err: string)
 */
static int l_task_result(lua_State *L) {
    lua_qrmi_resource_t *ud = check_resource(L, 1);
    const char *task_id = luaL_checkstring(L, 2);

    char *result = NULL;
    QrmiReturnCode rc = qrmi_resource_task_result(ud->handle, task_id, &result);
    if (rc != QRMI_RETURN_CODE_SUCCESS) return push_qrmi_error(L, rc);

    lua_pushstring(L, result);
    qrmi_string_free(result);
    return 1;
}

/**
 * @brief `resource:task_logs(task_id)` - Fetch a task's log messages.
 *
 * Wraps qrmi_resource_task_logs().
 *
 * Lua usage:
 * @code
 *   local logs, err = resource:task_logs(task_id)
 * @endcode
 *
 * @param L Lua state. Stack arguments:
 *   - [1] resource (qrmi.resource userdata)
 *   - [2] task_id (string) identifier returned by `resource:task_start()`
 * @return Number of values pushed onto the Lua stack.
 *         On success: 1 (logs: string)
 *         On failure: 2 (nil, err: string)
 */
static int l_task_logs(lua_State *L) {
    lua_qrmi_resource_t *ud = check_resource(L, 1);
    const char *task_id = luaL_checkstring(L, 2);

    char *logs = NULL;
    QrmiReturnCode rc = qrmi_resource_task_logs(ud->handle, task_id, &logs);
    if (rc != QRMI_RETURN_CODE_SUCCESS) return push_qrmi_error(L, rc);

    lua_pushstring(L, logs);
    qrmi_string_free(logs);
    return 1;
}

/**
 * @brief `resource:task_stop(task_id)` - Stop a running task.
 *
 * Wraps qrmi_resource_task_stop().
 *
 * Lua usage:
 * @code
 *   local ok, err = resource:task_stop(task_id)
 * @endcode
 *
 * @param L Lua state. Stack arguments:
 *   - [1] resource (qrmi.resource userdata)
 *   - [2] task_id (string) identifier returned by `resource:task_start()`
 * @return Number of values pushed onto the Lua stack.
 *         On success: 1 (ok: boolean, always true)
 *         On failure: 2 (nil, err: string)
 */
static int l_task_stop(lua_State *L) {
    lua_qrmi_resource_t *ud = check_resource(L, 1);
    const char *task_id = luaL_checkstring(L, 2);
    QrmiReturnCode rc = qrmi_resource_task_stop(ud->handle, task_id);
    if (rc != QRMI_RETURN_CODE_SUCCESS) return push_qrmi_error(L, rc);
    lua_pushboolean(L, 1);
    return 1;
}

/**
 * @brief `resource:metadata()` - Fetch the resource's metadata as a Lua table.
 *
 * Wraps qrmi_resource_metadata(), qrmi_resource_metadata_keys(), and
 * qrmi_resource_metadata_value(), flattening the result into a single
 * Lua table of key -> value strings. The underlying QrmiResourceMetadata
 * handle and all intermediate strings/arrays are freed before this
 * function returns, so no extra userdata/GC bookkeeping is needed on the
 * Lua side.
 *
 * Lua usage:
 * @code
 *   local meta, err = resource:metadata()
 *   print(meta.backend_name, meta.n_qubits)
 * @endcode
 *
 * @param L Lua state. Stack arguments: [1] resource (qrmi.resource userdata).
 * @return Number of values pushed onto the Lua stack.
 *         On success: 1 (metadata: table, string -> string)
 *         On failure: 2 (nil, err: string)
 */
static int l_metadata(lua_State *L) {
    lua_qrmi_resource_t *ud = check_resource(L, 1);

    QrmiResourceMetadata *metadata = NULL;
    QrmiReturnCode rc = qrmi_resource_metadata(ud->handle, &metadata);
    if (rc != QRMI_RETURN_CODE_SUCCESS) return push_qrmi_error(L, rc);

    size_t num_keys = 0;
    char **key_names = NULL;
    rc = qrmi_resource_metadata_keys(metadata, &num_keys, &key_names);
    if (rc != QRMI_RETURN_CODE_SUCCESS) {
        qrmi_resource_metadata_free(metadata);
        return push_qrmi_error(L, rc);
    }

    lua_newtable(L);
    for (size_t i = 0; i < num_keys; i++) {
        char *value = qrmi_resource_metadata_value(metadata, key_names[i]);
        lua_pushstring(L, key_names[i]);
        if (value) {
            lua_pushstring(L, value);
            qrmi_string_free(value);
        } else {
            lua_pushnil(L);
        }
        lua_settable(L, -3);
    }

    qrmi_string_array_free(num_keys, key_names);
    qrmi_resource_metadata_free(metadata);
    return 1;
}

/**
 * @brief `resource:target()` - Fetch the device's target information.
 *
 * Wraps qrmi_resource_target().
 *
 * Lua usage:
 * @code
 *   local target_json, err = resource:target()
 * @endcode
 *
 * @param L Lua state. Stack arguments: [1] resource (qrmi.resource userdata).
 * @return Number of values pushed onto the Lua stack.
 *         On success: 1 (target_json: string)
 *         On failure: 2 (nil, err: string)
 */
static int l_target(lua_State *L) {
    lua_qrmi_resource_t *ud = check_resource(L, 1);

    char *target = NULL;
    QrmiReturnCode rc = qrmi_resource_target(ud->handle, &target);
    if (rc != QRMI_RETURN_CODE_SUCCESS) return push_qrmi_error(L, rc);

    lua_pushstring(L, target);
    qrmi_string_free(target);
    return 1;
}

/**
 * @brief Release the underlying QRMI resource, if not already released.
 *
 * If a token is currently held (from `resource:acquire()`), it is released
 * first via qrmi_resource_release(), then the handle itself is freed via
 * qrmi_resource_free(). Safe to call multiple times; a no-op once the
 * handle is NULL.
 *
 * @param ud The resource's userdata payload.
 */
static void release_resource(lua_qrmi_resource_t *ud) {
    if (ud->handle == NULL) return;
    if (ud->acquisition_token) {
        qrmi_resource_release(ud->handle, ud->acquisition_token);
        free(ud->acquisition_token);
        ud->acquisition_token = NULL;
    }
    qrmi_resource_free(ud->handle);
    ud->handle = NULL;
}

/**
 * @brief `resource:free()` - Explicitly release and free the resource.
 *
 * Wraps release_resource(). Unlike the other methods, this does not
 * raise an error if the resource has already been freed (calling it
 * again is a harmless no-op).
 *
 * Lua usage:
 * @code
 *   resource:free()
 * @endcode
 *
 * @param L Lua state. Stack arguments: [1] resource (qrmi.resource userdata).
 * @return Always 0 (no values pushed).
 */
static int l_resource_free(lua_State *L) {
    lua_qrmi_resource_t *ud = (lua_qrmi_resource_t *)luaL_checkudata(L, 1, QRMI_RESOURCE_MT);
    release_resource(ud);
    return 0;
}

/**
 * @brief `__gc` metamethod - Safety net that auto-releases a forgotten resource.
 *
 * Invoked by the Lua garbage collector when a `qrmi.resource` userdata
 * becomes unreachable. Calls release_resource(), which is a no-op if
 * `resource:free()` was already called explicitly.
 *
 * @param L Lua state. Stack arguments: [1] resource (qrmi.resource userdata).
 * @return Always 0 (no values pushed).
 */
static int l_resource_gc(lua_State *L) {
    lua_qrmi_resource_t *ud = (lua_qrmi_resource_t *)luaL_checkudata(L, 1, QRMI_RESOURCE_MT);
    release_resource(ud);
    return 0;
}

/** @brief Method table installed on the `qrmi.resource` metatable's __index. */
static const luaL_Reg resource_methods[] = {
    {"is_accessible", l_is_accessible},
    {"acquire",       l_acquire},
    {"release",       l_release},
    {"task_start",    l_task_start},
    {"task_status",   l_task_status},
    {"task_result",   l_task_result},
    {"task_logs",     l_task_logs},
    {"task_stop",     l_task_stop},
    {"metadata",      l_metadata},
    {"target",        l_target},
    {"free",          l_resource_free},
    {"__gc",          l_resource_gc},
    {NULL, NULL}
};

/* =========================================================================
 * qrmi.config — completely independent from qrmi.resource above.
 * Wraps QrmiConfig / qrmi_config_load() and friends, used for reading
 * resource definitions out of a qrmi_config.json file. Has its own
 * lifecycle (load/free) unrelated to QrmiQuantumResource.
 * ========================================================================= */

/**
 * @brief `qrmi.load_config(filename)` - Load a qrmi_config.json file.
 *
 * Wraps qrmi_config_load().
 *
 * Lua usage:
 * @code
 *   local config, err = qrmi.load_config("/etc/slurm/qrmi_config.json")
 * @endcode
 *
 * @param L Lua state. Stack arguments: [1] filename (string) path to qrmi_config.json.
 * @return Number of values pushed onto the Lua stack.
 *         On success: 1 (config: qrmi.config userdata)
 *         On failure: 2 (nil, err: string)
 */
static int l_qrmi_load_config(lua_State *L) {
    const char *filename = luaL_checkstring(L, 1);

    QrmiConfig *handle = qrmi_config_load(filename);
    if (!handle) {
        const char *err = qrmi_get_last_error();
        lua_pushnil(L);
        lua_pushstring(L, err ? err : "qrmi_config_load failed");
        return 2;
    }

    lua_qrmi_config_t *ud = (lua_qrmi_config_t *)lua_newuserdata(L, sizeof(lua_qrmi_config_t));
    ud->handle = handle;
    luaL_getmetatable(L, QRMI_CONFIG_MT);
    lua_setmetatable(L, -2);
    return 1;
}

/**
 * @brief Fetch the lua_qrmi_config_t backing a `qrmi.config` userdata.
 *
 * Raises a Lua error (via luaL_error) if the config has already been freed.
 *
 * @param L   Lua state.
 * @param idx Stack index of the `qrmi.config` userdata argument.
 * @return Pointer to the config's userdata payload. Never returns NULL
 *         (raises a Lua error instead, which does not return control here).
 */
static lua_qrmi_config_t *check_config(lua_State *L, int idx) {
    lua_qrmi_config_t *ud = (lua_qrmi_config_t *)luaL_checkudata(L, idx, QRMI_CONFIG_MT);
    if (ud->handle == NULL) {
        luaL_error(L, "qrmi config already freed");
    }
    return ud;
}

/**
 * @brief `config:resource_def(resource_id)` - Look up a resource's definition.
 *
 * Wraps qrmi_config_resource_def_get(), converting the returned
 * QrmiResourceDef into a plain Lua table. The QrmiResourceDef itself is
 * freed via qrmi_config_resource_def_free() before this function returns.
 *
 * Lua usage:
 * @code
 *   local def, err = config:resource_def("ibm_kingston")
 *   -- def = {
 *   --   name = "ibm_kingston",
 *   --   type = "ibm-quantum-system",
 *   --   is_dynamic = false,
 *   --   environments = { QRMI_IBM_QUANTUM_TOKEN = "...", ... },
 *   -- }
 * @endcode
 *
 * @param L Lua state. Stack arguments:
 *   - [1] config (qrmi.config userdata)
 *   - [2] resource_id (string)
 * @return Number of values pushed onto the Lua stack.
 *         On success: 1 (def: table as described above)
 *         On failure: 2 (nil, err: string)
 */
static int l_config_resource_def(lua_State *L) {
    lua_qrmi_config_t *ud = check_config(L, 1);
    const char *resource_id = luaL_checkstring(L, 2);

    QrmiResourceDef *def = qrmi_config_resource_def_get(ud->handle, resource_id);
    if (!def) {
        const char *err = qrmi_get_last_error();
        lua_pushnil(L);
        lua_pushstring(L, err ? err : "qrmi_config_resource_def_get failed");
        return 2;
    }

    lua_newtable(L);

    lua_pushstring(L, def->name);
    lua_setfield(L, -2, "name");

    const char *type_str = qrmi_config_resource_type_to_str(def->type);
    lua_pushstring(L, type_str ? type_str : "unknown");
    lua_setfield(L, -2, "type");

    lua_pushboolean(L, def->is_dynamic);
    lua_setfield(L, -2, "is_dynamic");

    lua_newtable(L);
    for (size_t i = 0; i < def->environments.length; i++) {
        QrmiKeyValue *kv = &def->environments.variables[i];
        lua_pushstring(L, kv->key);
        lua_pushstring(L, kv->value);
        lua_settable(L, -3);
    }
    lua_setfield(L, -2, "environments");

    qrmi_config_resource_def_free(def);
    return 1;
}

/**
 * @brief Free the underlying QrmiConfig, if not already freed.
 *
 * Safe to call multiple times; a no-op once the handle is NULL.
 *
 * @param ud The config's userdata payload.
 */
static void release_config(lua_qrmi_config_t *ud) {
    if (ud->handle == NULL) return;
    qrmi_config_free(ud->handle);
    ud->handle = NULL;
}

/**
 * @brief `config:free()` - Explicitly free the config.
 *
 * Lua usage:
 * @code
 *   config:free()
 * @endcode
 *
 * @param L Lua state. Stack arguments: [1] config (qrmi.config userdata).
 * @return Always 0 (no values pushed).
 */
static int l_config_free(lua_State *L) {
    lua_qrmi_config_t *ud = (lua_qrmi_config_t *)luaL_checkudata(L, 1, QRMI_CONFIG_MT);
    release_config(ud);
    return 0;
}

/**
 * @brief `__gc` metamethod - Safety net that auto-frees a forgotten config.
 *
 * @param L Lua state. Stack arguments: [1] config (qrmi.config userdata).
 * @return Always 0 (no values pushed).
 */
static int l_config_gc(lua_State *L) {
    lua_qrmi_config_t *ud = (lua_qrmi_config_t *)luaL_checkudata(L, 1, QRMI_CONFIG_MT);
    release_config(ud);
    return 0;
}

/** @brief Method table installed on the `qrmi.config` metatable's __index. */
static const luaL_Reg config_methods[] = {
    {"resource_def", l_config_resource_def},
    {"free",         l_config_free},
    {"__gc",         l_config_gc},
    {NULL, NULL}
};

/** @brief Function table installed on the `qrmi` module table. */
static const luaL_Reg qrmi_functions[] = {
    {"new",         l_qrmi_new},
    {"load_config", l_qrmi_load_config},
    {NULL, NULL}
};

/**
 * @brief Module entry point, invoked by Lua's `require("qrmi")`.
 *
 * Registers the `qrmi.resource` metatable (with `__index` pointing at
 * itself so `resource:method()` calls dispatch through resource_methods)
 * and the completely independent `qrmi.config` metatable (dispatching
 * through config_methods), then returns the `qrmi` module table
 * (containing `qrmi.new` and `qrmi.load_config`).
 *
 * @param L Lua state.
 * @return Always 1 (the `qrmi` module table).
 */
int luaopen_qrmi(lua_State *L) {
    luaL_newmetatable(L, QRMI_RESOURCE_MT);
    lua_pushvalue(L, -1);
    lua_setfield(L, -2, "__index");
    luaL_setfuncs(L, resource_methods, 0);
    lua_pop(L, 1);

    luaL_newmetatable(L, QRMI_CONFIG_MT);
    lua_pushvalue(L, -1);
    lua_setfield(L, -2, "__index");
    luaL_setfuncs(L, config_methods, 0);
    lua_pop(L, 1);

    luaL_newlib(L, qrmi_functions);
    return 1;
}

