// SPDX-License-Identifier: Apache-2.0
// (C) Copyright IBM Corporation 2026
// Generated by: https://openapi-generator.tech

use crate::models;
use serde::{Deserialize, Serialize};

/// IqmServerJobError : Representation of a job error that occurred during the processing.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IqmServerJobError {
    /// Machine-readable reason code for the error
    #[serde(rename = "error_code")]
    pub error_code: String,
    /// Human-readable message describing the error.
    #[serde(rename = "message")]
    pub message: String,
    /// Source of the error (e.g. "iqm-server", "iqm-station-control")
    #[serde(rename = "source")]
    pub source: models::IqmServerJobErrorSource,
}

impl IqmServerJobError {
    pub fn new(
        error_code: String,
        message: String,
        source: models::IqmServerJobErrorSource,
    ) -> IqmServerJobError {
        IqmServerJobError {
            error_code,
            message,
            source,
        }
    }
}
