// SPDX-License-Identifier: Apache-2.0
// (C) Copyright IBM Corporation 2026
// Generated by: https://openapi-generator.tech

use serde::{Deserialize, Serialize};

/// Job error source (e.g. "iqm-server", "iqm-station-control")
pub type IqmServerJobErrorSource = String;
