// SPDX-License-Identifier: Apache-2.0
// (C) Copyright IBM Corporation 2026
// Generated by: https://openapi-generator.tech

use crate::models;
use serde::{Deserialize, Serialize};

/// IqmServerJobTimelineEvent : Representation of a single job timeline event.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IqmServerJobTimelineEvent {
    #[serde(rename = "source")]
    pub source: models::IqmServerJobErrorSource,
    /// Status of the job
    #[serde(rename = "status")]
    pub status: String,
    /// Timestamp when the event occurred
    #[serde(rename = "timestamp")]
    pub timestamp: chrono::DateTime<chrono::FixedOffset>,
}

impl IqmServerJobTimelineEvent {
    pub fn new(
        source: models::IqmServerJobErrorSource,
        status: String,
        timestamp: chrono::DateTime<chrono::FixedOffset>,
    ) -> IqmServerJobTimelineEvent {
        IqmServerJobTimelineEvent {
            source,
            status,
            timestamp,
        }
    }
}
