/*
 * Felis
 *
 * The Felis Cloud API lets you execute quantum circuits on emulators and real quantum hardware made by Alice & Bob.  To run a circuit with the API: - Create a job with \"Create Job\", targeting a specific backend (listed by  \"List Targets\"). - Upload the input quantum code of your job in [QIR format](https://github.com/qir-alliance/qir-spec) with \"Upload Input\". - Monitor the job's status with \"Get Job\". - Read the results with \"Download Output\".  The execution stack includes a transpilation step to adapt the input code to the target's gate set. The result of the transpilation can be seen with \"Download Transpiled\".  This API is used by [Alice & Bob's Qiskit provider](https://github.com/Alice-Bob-SW/qiskit-alice-bob-provider), which also serves as a reference implementation.  Using this API requires an API key in the authorization header. Please reach out to Alice & Bob athttps://alice-bob.com/products/quantum-cloud-felis to learn how to get one.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum EventType {
    #[serde(rename = "CREATED")]
    Created,
    #[serde(rename = "FETCHING_INPUT")]
    FetchingInput,
    #[serde(rename = "INPUT_READY")]
    InputReady,
    #[serde(rename = "COMPILING")]
    Compiling,
    #[serde(rename = "COMPILED")]
    Compiled,
    #[serde(rename = "COMPILATION_FAILED")]
    CompilationFailed,
    #[serde(rename = "TRANSPILING")]
    Transpiling,
    #[serde(rename = "TRANSPILED")]
    Transpiled,
    #[serde(rename = "TRANSPILATION_FAILED")]
    TranspilationFailed,
    #[serde(rename = "EXECUTING")]
    Executing,
    #[serde(rename = "SUCCEEDED")]
    Succeeded,
    #[serde(rename = "EXECUTION_FAILED")]
    ExecutionFailed,
    #[serde(rename = "CANCELLED")]
    Cancelled,
    #[serde(rename = "TIMED_OUT")]
    TimedOut,

}

impl std::fmt::Display for EventType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Created => write!(f, "CREATED"),
            Self::FetchingInput => write!(f, "FETCHING_INPUT"),
            Self::InputReady => write!(f, "INPUT_READY"),
            Self::Compiling => write!(f, "COMPILING"),
            Self::Compiled => write!(f, "COMPILED"),
            Self::CompilationFailed => write!(f, "COMPILATION_FAILED"),
            Self::Transpiling => write!(f, "TRANSPILING"),
            Self::Transpiled => write!(f, "TRANSPILED"),
            Self::TranspilationFailed => write!(f, "TRANSPILATION_FAILED"),
            Self::Executing => write!(f, "EXECUTING"),
            Self::Succeeded => write!(f, "SUCCEEDED"),
            Self::ExecutionFailed => write!(f, "EXECUTION_FAILED"),
            Self::Cancelled => write!(f, "CANCELLED"),
            Self::TimedOut => write!(f, "TIMED_OUT"),
        }
    }
}

impl Default for EventType {
    fn default() -> EventType {
        Self::Created
    }
}

