/*
 * Felis
 *
 * The Felis Cloud API lets you execute quantum circuits on emulators and real quantum hardware made by Alice & Bob.  To run a circuit with the API: - Create a job with \"Create Job\", targeting a specific backend (listed by  \"List Targets\"). - Upload the input quantum code of your job in [QIR format](https://github.com/qir-alliance/qir-spec) with \"Upload Input\". - Monitor the job's status with \"Get Job\". - Read the results with \"Download Output\".  The execution stack includes a transpilation step to adapt the input code to the target's gate set. The result of the transpilation can be seen with \"Download Transpiled\".  This API is used by [Alice & Bob's Qiskit provider](https://github.com/Alice-Bob-SW/qiskit-alice-bob-provider), which also serves as a reference implementation.  Using this API requires an API key in the authorization header. Please reach out to Alice & Bob athttps://alice-bob.com/products/quantum-cloud-felis to learn how to get one.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExternalJob {
    #[serde(rename = "inputDataFormat", deserialize_with = "Option::deserialize")]
    pub input_data_format: Option<serde_json::Value>,
    #[serde(rename = "outputDataFormat", deserialize_with = "Option::deserialize")]
    pub output_data_format: Option<serde_json::Value>,
    #[serde(rename = "target")]
    pub target: String,
    #[serde(rename = "inputParams")]
    pub input_params: serde_json::Value,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "userName")]
    pub user_name: String,
    #[serde(rename = "userId")]
    pub user_id: String,
    #[serde(rename = "organizationName")]
    pub organization_name: String,
    #[serde(rename = "events")]
    pub events: Vec<models::JobEvent>,
    #[serde(rename = "errors")]
    pub errors: Vec<models::JobError>,
}

impl ExternalJob {
    pub fn new(input_data_format: Option<serde_json::Value>, output_data_format: Option<serde_json::Value>, target: String, input_params: serde_json::Value, id: String, user_name: String, user_id: String, organization_name: String, events: Vec<models::JobEvent>, errors: Vec<models::JobError>) -> ExternalJob {
        ExternalJob {
            input_data_format,
            output_data_format,
            target,
            input_params,
            id,
            user_name,
            user_id,
            organization_name,
            events,
            errors,
        }
    }
}

