/*
 * Felis
 *
 * The Felis Cloud API lets you execute quantum circuits on emulators and real quantum hardware made by Alice & Bob.  To run a circuit with the API: - Create a job with \"Create Job\", targeting a specific backend (listed by  \"List Targets\"). - Upload the input quantum code of your job in [QIR format](https://github.com/qir-alliance/qir-spec) with \"Upload Input\". - Monitor the job's status with \"Get Job\". - Read the results with \"Download Output\".  The execution stack includes a transpilation step to adapt the input code to the target's gate set. The result of the transpilation can be seen with \"Download Transpiled\".  This API is used by [Alice & Bob's Qiskit provider](https://github.com/Alice-Bob-SW/qiskit-alice-bob-provider), which also serves as a reference implementation.  Using this API requires an API key in the authorization header. Please reach out to Alice & Bob athttps://alice-bob.com/products/quantum-cloud-felis to learn how to get one.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InputParamConfiguration {
    #[serde(rename = "required")]
    pub required: bool,
    #[serde(rename = "type")]
    pub r#type: Type,
    #[serde(rename = "default", deserialize_with = "Option::deserialize")]
    pub default: Option<Box<models::Default>>,
    #[serde(rename = "constraints")]
    pub constraints: Vec<models::InputParamRangeConstraint>,
}

impl InputParamConfiguration {
    pub fn new(required: bool, r#type: Type, default: Option<models::Default>, constraints: Vec<models::InputParamRangeConstraint>) -> InputParamConfiguration {
        InputParamConfiguration {
            required,
            r#type,
            default: if let Some(x) = default {Some(Box::new(x))} else {None},
            constraints,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "float")]
    Float,
    #[serde(rename = "int")]
    Int,
    #[serde(rename = "bool")]
    Bool,
}

impl Default for Type {
    fn default() -> Type {
        Self::Float
    }
}

