/*
 * Qiskit Runtime API
 *
 * The Qiskit Runtime API description
 *
 * The version of the OpenAPI document: 0.31.10
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AnalyticsFilters200ResponsePlansInner {
    #[serde(rename = "name")]
    pub name: String,
}

impl AnalyticsFilters200ResponsePlansInner {
    pub fn new(name: String) -> AnalyticsFilters200ResponsePlansInner {
        AnalyticsFilters200ResponsePlansInner { name }
    }
}
