/*
 * Qiskit Runtime API
 *
 * The Qiskit Runtime API description
 *
 * The version of the OpenAPI document: 0.31.10
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AnalyticsFilters200Response {
    #[serde(rename = "backends")]
    pub backends: Vec<models::AnalyticsFilters200ResponseBackendsInner>,
    #[serde(rename = "instances")]
    pub instances: Vec<models::AnalyticsFilters200ResponseInstancesInner>,
    #[serde(rename = "users")]
    pub users: Vec<models::AnalyticsFilters200ResponseUsersInner>,
    #[serde(rename = "plans")]
    pub plans: Vec<models::AnalyticsFilters200ResponsePlansInner>,
}

impl AnalyticsFilters200Response {
    pub fn new(
        backends: Vec<models::AnalyticsFilters200ResponseBackendsInner>,
        instances: Vec<models::AnalyticsFilters200ResponseInstancesInner>,
        users: Vec<models::AnalyticsFilters200ResponseUsersInner>,
        plans: Vec<models::AnalyticsFilters200ResponsePlansInner>,
    ) -> AnalyticsFilters200Response {
        AnalyticsFilters200Response {
            backends,
            instances,
            users,
            plans,
        }
    }
}
