/*
 * Qiskit Runtime API
 *
 * The Qiskit Runtime API description
 *
 * The version of the OpenAPI document: 0.31.10
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CreateSessionRequestOneOf : Request to create a session. Only for use with IBM Cloud Channel.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateSessionRequestOneOf {
    /// The maximum time (in seconds) for the session to run, subject to plan limits.
    #[serde(rename = "max_ttl", skip_serializing_if = "Option::is_none")]
    pub max_ttl: Option<i32>,
    /// Execution mode to run the session in
    #[serde(rename = "mode")]
    pub mode: Mode,
    /// Backend name
    #[serde(rename = "backend", skip_serializing_if = "Option::is_none")]
    pub backend: Option<String>,
    /// Backend name (fallback)
    #[serde(rename = "backend_name", skip_serializing_if = "Option::is_none")]
    pub backend_name: Option<String>,
}

impl CreateSessionRequestOneOf {
    /// Request to create a session. Only for use with IBM Cloud Channel.
    pub fn new(mode: Mode) -> CreateSessionRequestOneOf {
        CreateSessionRequestOneOf {
            max_ttl: None,
            mode,
            backend: None,
            backend_name: None,
        }
    }
}
/// Execution mode to run the session in
#[derive(
    Clone, Copy, Debug, Default, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize,
)]
pub enum Mode {
    #[serde(rename = "batch")]
    #[default]
    Batch,
    #[serde(rename = "dedicated")]
    Dedicated,
}
