/*
 * Qiskit Runtime API
 *
 * The Qiskit Runtime API description
 *
 * The version of the OpenAPI document: 0.31.10
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// EstimatorV2InputOptionsResiliencePecNoiseGain : The amount by which to scale the noise
/// The amount by which to scale the noise
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum EstimatorV2InputOptionsResiliencePecNoiseGain {
    Number(f64),
    String(String),
}

impl Default for EstimatorV2InputOptionsResiliencePecNoiseGain {
    fn default() -> Self {
        Self::Number(Default::default())
    }
}
