/*
 * Qiskit Runtime API
 *
 * The Qiskit Runtime API description
 *
 * The version of the OpenAPI document: 0.31.10
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// EstimatorV2InputOptionsResilienceZneExtrapolator : Extrapolator(s) to try (in order) for extrapolating to zero noise
/// Extrapolator(s) to try (in order) for extrapolating to zero noise
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum EstimatorV2InputOptionsResilienceZneExtrapolator {
    ArrayVecString(Vec<String>),
    String(String),
}

impl Default for EstimatorV2InputOptionsResilienceZneExtrapolator {
    fn default() -> Self {
        Self::ArrayVecString(Default::default())
    }
}
