/*
 * Qiskit Runtime API
 *
 * The Qiskit Runtime API description
 *
 * The version of the OpenAPI document: 0.31.10
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// EstimatorV2InputOptionsResiliencePec : Additional probabilistic error cancellation mitigation options
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EstimatorV2InputOptionsResiliencePec {
    #[serde(
        rename = "max_overhead",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub max_overhead: Option<Option<f64>>,
    #[serde(rename = "noise_gain", skip_serializing_if = "Option::is_none")]
    pub noise_gain: Option<Box<models::EstimatorV2InputOptionsResiliencePecNoiseGain>>,
}

impl EstimatorV2InputOptionsResiliencePec {
    /// Additional probabilistic error cancellation mitigation options
    pub fn new() -> EstimatorV2InputOptionsResiliencePec {
        EstimatorV2InputOptionsResiliencePec {
            max_overhead: None,
            noise_gain: None,
        }
    }
}
