/*
 * Qiskit Runtime API
 *
 * The Qiskit Runtime API description
 *
 * The version of the OpenAPI document: 0.31.10
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// EstimatorV2InputOptions : Options for V2 Estimator
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EstimatorV2InputOptions {
    /// Seed used to control sampling
    #[serde(
        rename = "seed_estimator",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub seed_estimator: Option<Option<i32>>,
    /// The default precision to use if a precision is not specified for a PUB or for this job.
    #[serde(rename = "default_precision", skip_serializing_if = "Option::is_none")]
    pub default_precision: Option<f64>,
    /// The total number of shots to use per circuit per configuration. If set, this value overrides default_precision.
    #[serde(
        rename = "default_shots",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub default_shots: Option<Option<i32>>,
    #[serde(
        rename = "dynamical_decoupling",
        skip_serializing_if = "Option::is_none"
    )]
    pub dynamical_decoupling: Option<Box<models::EstimatorV2InputOptionsDynamicalDecoupling>>,
    #[serde(rename = "resilience", skip_serializing_if = "Option::is_none")]
    pub resilience: Option<Box<models::EstimatorV2InputOptionsResilience>>,
    #[serde(rename = "execution", skip_serializing_if = "Option::is_none")]
    pub execution: Option<Box<models::EstimatorV2InputOptionsExecution>>,
    #[serde(rename = "twirling", skip_serializing_if = "Option::is_none")]
    pub twirling: Option<Box<models::SamplerV2InputOptionsTwirling>>,
    #[serde(rename = "simulator", skip_serializing_if = "Option::is_none")]
    pub simulator: Option<Box<models::SamplerV2InputOptionsSimulator>>,
    /// Experimental options.
    #[serde(rename = "experimental", skip_serializing_if = "Option::is_none")]
    pub experimental: Option<serde_json::Value>,
}

impl EstimatorV2InputOptions {
    /// Options for V2 Estimator
    pub fn new() -> EstimatorV2InputOptions {
        EstimatorV2InputOptions {
            seed_estimator: None,
            default_precision: None,
            default_shots: None,
            dynamical_decoupling: None,
            resilience: None,
            execution: None,
            twirling: None,
            simulator: None,
            experimental: None,
        }
    }
}
