/*
 * Qiskit Runtime API
 *
 * The Qiskit Runtime API description
 *
 * The version of the OpenAPI document: 0.31.10
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FindInstanceWorkloads400ResponseErrorsInner {
    #[serde(rename = "code")]
    pub code: f64,
    #[serde(rename = "message")]
    pub message: String,
    #[serde(rename = "solution")]
    pub solution: String,
    #[serde(rename = "more_info")]
    pub more_info: String,
}

impl FindInstanceWorkloads400ResponseErrorsInner {
    pub fn new(
        code: f64,
        message: String,
        solution: String,
        more_info: String,
    ) -> FindInstanceWorkloads400ResponseErrorsInner {
        FindInstanceWorkloads400ResponseErrorsInner {
            code,
            message,
            solution,
            more_info,
        }
    }
}
