/*
 * Qiskit Runtime API
 *
 * The Qiskit Runtime API description
 *
 * The version of the OpenAPI document: 0.31.10
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetAccount200Response : Configuration for an account managed by the IBM Qiskit Runtime service.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetAccount200Response {
    /// The list of configurations for the account per plan
    #[serde(rename = "plans")]
    pub plans: Vec<models::GetAccount200ResponsePlansInner>,
}

impl GetAccount200Response {
    /// Configuration for an account managed by the IBM Qiskit Runtime service.
    pub fn new(plans: Vec<models::GetAccount200ResponsePlansInner>) -> GetAccount200Response {
        GetAccount200Response { plans }
    }
}
