/*
 * Qiskit Runtime API
 *
 * The Qiskit Runtime API description
 *
 * The version of the OpenAPI document: 0.31.10
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetUsage200ResponseUsagePeriod : Start and end time of the usage period
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetUsage200ResponseUsagePeriod {
    /// The start time of the usage
    #[serde(rename = "start_time", skip_serializing_if = "Option::is_none")]
    pub start_time: Option<String>,
    /// The end time of the usage
    #[serde(rename = "end_time", skip_serializing_if = "Option::is_none")]
    pub end_time: Option<String>,
}

impl GetUsage200ResponseUsagePeriod {
    /// Start and end time of the usage period
    pub fn new() -> GetUsage200ResponseUsagePeriod {
        GetUsage200ResponseUsagePeriod {
            start_time: None,
            end_time: None,
        }
    }
}
