/*
 * Qiskit Runtime API
 *
 * The Qiskit Runtime API description
 *
 * The version of the OpenAPI document: 0.31.10
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SamplerV2InputOptions : Options for V2 Sampler
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SamplerV2InputOptions {
    /// The default number of shots to use if none are specified in the PUBs
    #[serde(rename = "default_shots", skip_serializing_if = "Option::is_none")]
    pub default_shots: Option<i32>,
    #[serde(
        rename = "dynamical_decoupling",
        skip_serializing_if = "Option::is_none"
    )]
    pub dynamical_decoupling: Option<Box<models::SamplerV2InputOptionsDynamicalDecoupling>>,
    #[serde(rename = "execution", skip_serializing_if = "Option::is_none")]
    pub execution: Option<Box<models::SamplerV2InputOptionsExecution>>,
    #[serde(rename = "twirling", skip_serializing_if = "Option::is_none")]
    pub twirling: Option<Box<models::SamplerV2InputOptionsTwirling>>,
    #[serde(rename = "simulator", skip_serializing_if = "Option::is_none")]
    pub simulator: Option<Box<models::SamplerV2InputOptionsSimulator>>,
    /// Experimental options.
    #[serde(rename = "experimental", skip_serializing_if = "Option::is_none")]
    pub experimental: Option<serde_json::Value>,
}

impl SamplerV2InputOptions {
    /// Options for V2 Sampler
    pub fn new() -> SamplerV2InputOptions {
        SamplerV2InputOptions {
            default_shots: None,
            dynamical_decoupling: None,
            execution: None,
            twirling: None,
            simulator: None,
            experimental: None,
        }
    }
}
