/*
 * Qiskit Runtime API
 *
 * The Qiskit Runtime API description
 *
 * The version of the OpenAPI document: 0.31.10
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SamplerV2InputOptionsSimulator : Simulator options
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SamplerV2InputOptionsSimulator {
    /// Noise model for the simulator.
    #[serde(
        rename = "noise_model",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub noise_model: Option<Option<serde_json::Value>>,
    /// Random seed to control sampling.
    #[serde(
        rename = "seed_simulator",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub seed_simulator: Option<Option<i32>>,
    /// Directed coupling map to target in mapping.
    #[serde(
        rename = "coupling_map",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub coupling_map: Option<Option<Vec<serde_json::Value>>>,
    /// List of basis gate names to unroll to.
    #[serde(rename = "basis_gates", skip_serializing_if = "Option::is_none")]
    pub basis_gates: Option<Vec<String>>,
}

impl SamplerV2InputOptionsSimulator {
    /// Simulator options
    pub fn new() -> SamplerV2InputOptionsSimulator {
        SamplerV2InputOptionsSimulator {
            noise_model: None,
            seed_simulator: None,
            coupling_map: None,
            basis_gates: None,
        }
    }
}
