/*
 * Qiskit Runtime API
 *
 * The Qiskit Runtime API description
 *
 * The version of the OpenAPI document: 0.31.10
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SamplerV2InputPubsInner {}

impl SamplerV2InputPubsInner {
    pub fn new() -> SamplerV2InputPubsInner {
        SamplerV2InputPubsInner {}
    }
}
