/*
 * Qiskit Runtime API
 *
 * The Qiskit Runtime API description
 *
 * The version of the OpenAPI document: 0.31.10
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CreateJob200Response : Response when creating a job
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateJob200Response {
    /// Job ID
    #[serde(rename = "id")]
    pub id: String,
    /// Backend selected to run job
    #[serde(rename = "backend")]
    pub backend: String,
    /// Id of the session associated with the job
    #[serde(rename = "session_id", skip_serializing_if = "Option::is_none")]
    pub session_id: Option<String>,
    /// When set to true, input parameters are not returned, and the results can only be read once. After the job is completed, input parameters are deleted from the service. After the results are read, they are deleted from the service. When set to false, the input parameters and results follow the standard retention behavior of the API. Only returned in the response if the value is true, otherwise it is omitted.
    #[serde(rename = "private", skip_serializing_if = "Option::is_none")]
    pub private: Option<bool>,
    /// The ID of the calibration used for the job
    #[serde(rename = "calibration_id", skip_serializing_if = "Option::is_none")]
    pub calibration_id: Option<String>,
}

impl CreateJob200Response {
    /// Response when creating a job
    pub fn new(id: String, backend: String) -> CreateJob200Response {
        CreateJob200Response {
            id,
            backend,
            session_id: None,
            private: None,
            calibration_id: None,
        }
    }
}
