/*
 * Qiskit Runtime API
 *
 * The Qiskit Runtime API description
 *
 * The version of the OpenAPI document: 0.31.10
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreateJobRequestOneOfAllOfParams {
    SamplerV2Input(Box<models::SamplerV2Input>),
    EstimatorV2Input(Box<models::EstimatorV2Input>),
    NoiseLearnerInput(Box<models::NoiseLearnerInput>),
}

impl Default for CreateJobRequestOneOfAllOfParams {
    fn default() -> Self {
        Self::SamplerV2Input(Default::default())
    }
}
/// For NoiseLearner, should always be 2
#[derive(
    Clone, Copy, Debug, Default, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize,
)]
pub enum Version {
    #[serde(rename = "2")]
    #[default]
    Variant2,
}
