/*
 * Qiskit Runtime API
 *
 * The Qiskit Runtime API description
 *
 * The version of the OpenAPI document: 0.31.10
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// EstimatorV2InputOptionsResilienceMeasureNoiseLearningShotsPerRandomization : The number of shots to use for the learning experiment per random circuit.
/// The number of shots to use for the learning experiment per random circuit.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum EstimatorV2InputOptionsResilienceMeasureNoiseLearningShotsPerRandomization {
    Integer(i32),
    String(String),
}

impl Default for EstimatorV2InputOptionsResilienceMeasureNoiseLearningShotsPerRandomization {
    fn default() -> Self {
        Self::Integer(Default::default())
    }
}
