/*
 * Qiskit Runtime API
 *
 * The Qiskit Runtime API description
 *
 * The version of the OpenAPI document: 0.31.10
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// EstimatorV2Input : The input for an EstimatorV2 API call
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EstimatorV2Input {
    /// Primitive Unit Blocs of data. Each PUB is of the form (Circuit, Observables, Parameters, Precision) where the circuit and observables are required, parameters should be passed only for parametrized circuits, and precision is optional
    #[serde(rename = "pubs")]
    pub pubs: Vec<Vec<serde_json::Value>>,
    #[serde(rename = "options", skip_serializing_if = "Option::is_none")]
    pub options: Option<Box<models::EstimatorV2InputOptions>>,
    /// How much resilience to build against errors
    #[serde(rename = "resilience_level", skip_serializing_if = "Option::is_none")]
    pub resilience_level: Option<i32>,
    /// Default precision level which applies to all PUBs without precision. This overrides default_precision and default_shots specified in options.
    #[serde(
        rename = "precision",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub precision: Option<Option<f64>>,
    /// If True, returns a qiskit-style output, meant to be parsed using the runtime result decoder, or resort to returning pure JSON results (resulting in larger objects)
    #[serde(rename = "support_qiskit", skip_serializing_if = "Option::is_none")]
    pub support_qiskit: Option<bool>,
    /// For EstimatorV2, version should always be 2
    #[serde(rename = "version")]
    pub version: i32,
}

impl EstimatorV2Input {
    /// The input for an EstimatorV2 API call
    pub fn new(pubs: Vec<Vec<serde_json::Value>>) -> EstimatorV2Input {
        EstimatorV2Input {
            pubs,
            options: None,
            resilience_level: None,
            precision: None,
            support_qiskit: None,
            version: 2,
        }
    }
}
