/*
 * Qiskit Runtime API
 *
 * The Qiskit Runtime API description
 *
 * The version of the OpenAPI document: 0.31.10
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// EstimatorV2InputOptionsResilienceMeasureNoiseLearning : Additional measurement noise learning options
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EstimatorV2InputOptionsResilienceMeasureNoiseLearning {
    /// The number of random circuits to draw for the measurement learning experiment
    #[serde(rename = "num_randomizations", skip_serializing_if = "Option::is_none")]
    pub num_randomizations: Option<i32>,
    #[serde(
        rename = "shots_per_randomization",
        skip_serializing_if = "Option::is_none"
    )]
    pub shots_per_randomization: Option<
        Box<models::EstimatorV2InputOptionsResilienceMeasureNoiseLearningShotsPerRandomization>,
    >,
}

impl EstimatorV2InputOptionsResilienceMeasureNoiseLearning {
    /// Additional measurement noise learning options
    pub fn new() -> EstimatorV2InputOptionsResilienceMeasureNoiseLearning {
        EstimatorV2InputOptionsResilienceMeasureNoiseLearning {
            num_randomizations: None,
            shots_per_randomization: None,
        }
    }
}
