/*
 * Qiskit Runtime API
 *
 * The Qiskit Runtime API description
 *
 * The version of the OpenAPI document: 0.31.10
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// EstimatorV2InputOptionsResilience : Advanced resilience options to fine tune the resilience strategy
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EstimatorV2InputOptionsResilience {
    /// Whether to enable measurement error mitigation method
    #[serde(rename = "measure_mitigation", skip_serializing_if = "Option::is_none")]
    pub measure_mitigation: Option<bool>,
    #[serde(
        rename = "measure_noise_learning",
        skip_serializing_if = "Option::is_none"
    )]
    pub measure_noise_learning:
        Option<Box<models::EstimatorV2InputOptionsResilienceMeasureNoiseLearning>>,
    /// Whether to turn on Zero Noise Extrapolation error mitigation method
    #[serde(rename = "zne_mitigation", skip_serializing_if = "Option::is_none")]
    pub zne_mitigation: Option<bool>,
    #[serde(rename = "zne", skip_serializing_if = "Option::is_none")]
    pub zne: Option<Box<models::EstimatorV2InputOptionsResilienceZne>>,
    /// Whether to turn on Probabilistic Error Cancellation error mitigation method
    #[serde(rename = "pec_mitigation", skip_serializing_if = "Option::is_none")]
    pub pec_mitigation: Option<bool>,
    #[serde(rename = "pec", skip_serializing_if = "Option::is_none")]
    pub pec: Option<Box<models::EstimatorV2InputOptionsResiliencePec>>,
    #[serde(
        rename = "layer_noise_learning",
        skip_serializing_if = "Option::is_none"
    )]
    pub layer_noise_learning:
        Option<Box<models::EstimatorV2InputOptionsResilienceLayerNoiseLearning>>,
    /// A NoiseLearnerResult or a sequence of LayerError objects, or ``None`` to invoke a noise-learning stage when necessary.
    #[serde(
        rename = "layer_noise_model",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub layer_noise_model: Option<Option<serde_json::Value>>,
}

impl EstimatorV2InputOptionsResilience {
    /// Advanced resilience options to fine tune the resilience strategy
    pub fn new() -> EstimatorV2InputOptionsResilience {
        EstimatorV2InputOptionsResilience {
            measure_mitigation: None,
            measure_noise_learning: None,
            zne_mitigation: None,
            zne: None,
            pec_mitigation: None,
            pec: None,
            layer_noise_learning: None,
            layer_noise_model: None,
        }
    }
}
