/*
 * Qiskit Runtime API
 *
 * The Qiskit Runtime API description
 *
 * The version of the OpenAPI document: 0.31.10
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FindInstanceWorkloads400Response {
    #[serde(rename = "errors")]
    pub errors: Vec<models::FindInstanceWorkloads400ResponseErrorsInner>,
}

impl FindInstanceWorkloads400Response {
    pub fn new(
        errors: Vec<models::FindInstanceWorkloads400ResponseErrorsInner>,
    ) -> FindInstanceWorkloads400Response {
        FindInstanceWorkloads400Response { errors }
    }
}
