/*
 * Qiskit Runtime API
 *
 * The Qiskit Runtime API description
 *
 * The version of the OpenAPI document: 0.31.10
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// NoiseLearnerInput : The input for a NoiseLearner API call
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NoiseLearnerInput {
    /// The circuits on which to perform noise learning.
    #[serde(rename = "circuits")]
    pub circuits: Vec<serde_json::Value>,
    #[serde(rename = "options", skip_serializing_if = "Option::is_none")]
    pub options: Option<Box<models::NoiseLearnerInputOptions>>,
    /// For NoiseLearner, should always be 2
    #[serde(rename = "version")]
    pub version: i32,
}

impl NoiseLearnerInput {
    /// The input for a NoiseLearner API call
    pub fn new(circuits: Vec<serde_json::Value>) -> NoiseLearnerInput {
        NoiseLearnerInput {
            circuits,
            options: None,
            version: 2,
        }
    }
}
