/*
 * Qiskit Runtime API
 *
 * The Qiskit Runtime API description
 *
 * The version of the OpenAPI document: 0.31.10
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ReplaceInstanceConfigurationRequest : instance configuration update
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReplaceInstanceConfigurationRequest {
    /// This field can be null or an integer. Use null to reset/remove the instance limit.
    #[serde(rename = "instance_limit", skip_serializing_if = "Option::is_none")]
    pub instance_limit: Option<i32>,
}

impl ReplaceInstanceConfigurationRequest {
    /// instance configuration update
    pub fn new() -> ReplaceInstanceConfigurationRequest {
        ReplaceInstanceConfigurationRequest {
            instance_limit: None,
        }
    }
}
