/*
 * Qiskit Runtime API
 *
 * The Qiskit Runtime API description
 *
 * The version of the OpenAPI document: 0.31.10
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SamplerV2InputOptionsTwirlingNumRandomizations : The number of random samples to use when twirling or performing sampled mitigation
/// The number of random samples to use when twirling or performing sampled mitigation
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum SamplerV2InputOptionsTwirlingNumRandomizations {
    Integer(i32),
    String(String),
}

impl Default for SamplerV2InputOptionsTwirlingNumRandomizations {
    fn default() -> Self {
        Self::Integer(Default::default())
    }
}
