/*
 * Qiskit Runtime API
 *
 * The Qiskit Runtime API description
 *
 * The version of the OpenAPI document: 0.31.10
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SamplerV2InputOptionsTwirlingShotsPerRandomization : The number of shots to run for each random sample
/// The number of shots to run for each random sample
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum SamplerV2InputOptionsTwirlingShotsPerRandomization {
    Integer(i32),
    String(String),
}

impl Default for SamplerV2InputOptionsTwirlingShotsPerRandomization {
    fn default() -> Self {
        Self::Integer(Default::default())
    }
}
