# SPDX-License-Identifier: Apache-2.0
# (C) Copyright IBM Corporation 2026
# RPM spec file for the Quantum Resource Management Interface (QRMI) shared library
#
# Packages produced:
#   libqrmi       - runtime shared library (libqrmi.so.%{version}, libqrmi.so.0)
#   libqrmi-devel - development files (libqrmi.so symlink + qrmi.h)
#
# Build recommendation:
#   ./run_in_container.sh make libqrmi-rpm
#
# The version is intentionally not hardcoded in the spec file, it is supplied
# through the Makefile

# Disable automatic debuginfo/debugsource package generation
%global debug_package %{nil}

# ABI major version — bump this when a breaking ABI change is made,
# independently of the package version in Cargo.toml.
%global abi_major 0

Name:           libqrmi
Version:        %{version}
Release:        1%{?dist}
Summary:        Vendor-agnostic C shared library and header file for controlling quantum computing resources
License:        Apache-2.0
URL:            https://github.com/qiskit-community/qrmi
Source0:        qrmi-%{version}.tar.gz
Source1:        qrmi-%{version}-vendor.tar.gz

BuildRequires:  gcc
BuildRequires:  make
# Ensure the build host is RHEL 8 (glibc 2.28) or newer
BuildRequires:  glibc >= 2.28
BuildRequires:  pkg-config

Requires:       glibc >= 2.28

%description
QRMI (Quantum Resource Management Interface) is a vendor-agnostic shared
library that provides a unified C API (libqrmi.so / qrmi.h) for acquiring,
controlling, and monitoring quantum computing resources from multiple
vendors.

%package        devel
Summary:        Development files for libqrmi
Requires:       %{name}%{?_isa} = %{version}-%{release}

%description    devel
Header file and unversioned shared-library symlink for building
applications against libqrmi.

# ---------------------------------------------------------------------------
# Prep
# ---------------------------------------------------------------------------
%prep
%autosetup -n qrmi-%{version}

# Unpack the vendored Rust dependencies
tar xf %{SOURCE1}

# Configure Cargo to use the vendored sources (offline build)
mkdir -p .cargo
cat > .cargo/config.toml << 'EOF'
[source.crates-io]
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"
EOF

# ---------------------------------------------------------------------------
# Build
# ---------------------------------------------------------------------------
%build
# Source the Rust environment if installed via rustup
[ -f "$HOME/.cargo/env" ] && . "$HOME/.cargo/env"

# Rust's toolchain does not natively manage SONAME fields out-of-the-box for cdylibs.
# Embed SONAME in the ELF so RPM's find-provides automatically emits
# libqrmi.so.{abi_major}()(64bit) and find-requires on consumers matches it correctly.
RUSTFLAGS="-Clink-arg=-Wl,-soname,libqrmi.so.%{abi_major}" make build

# ---------------------------------------------------------------------------
# Install
# ---------------------------------------------------------------------------
%install
install -d %{buildroot}%{_libdir}
install -d %{buildroot}%{_includedir}

# Shared library
install -m 0755 target/release/libqrmi.so \
    %{buildroot}%{_libdir}/libqrmi.so.%{version}
%{__ln_s} libqrmi.so.%{version} %{buildroot}%{_libdir}/libqrmi.so.%{abi_major}
%{__ln_s} libqrmi.so.%{abi_major} %{buildroot}%{_libdir}/libqrmi.so

# C header (generated by cbindgen during the cargo build)
install -m 0644 qrmi.h \
    %{buildroot}%{_includedir}/qrmi.h

# ---------------------------------------------------------------------------
# Post-install / post-uninstall ldconfig triggers
# ---------------------------------------------------------------------------
%ldconfig_scriptlets

# ---------------------------------------------------------------------------
# Files
# ---------------------------------------------------------------------------
%files
%license LICENSE.txt
%doc README.md INSTALL.md
%{_libdir}/libqrmi.so.%{version}
%{_libdir}/libqrmi.so.%{abi_major}

%files devel
%{_libdir}/libqrmi.so
%{_includedir}/qrmi.h

# ---------------------------------------------------------------------------
# Changelog
# ---------------------------------------------------------------------------
%changelog
* %(date "+%a %b %d %Y") QRMI - %{version}-%{release}
- Auto generated changelog entry