# SPDX-License-Identifier: Apache-2.0
# (C) Copyright IBM Corporation 2026
# RPM spec file for the Quantum Resource Management Interface (QRMI) shared library
#
# Packages produced:
#   libqrmi          - shared library (libqrmi.so) and C header (qrmi.h)
#
# Build requirements:
#   - If you are not using the "./run_in_container.sh", make sure you the 
#     right Rust version is installed (see Cargo.toml)
#
# Usage:
#   ./run_in_container.sh make libqrmi-rpm
#
# The version is intentionally not hardcoded here. It must be supplied by the
# caller via --define so that Cargo.toml remains the single source of truth.

# Disable automatic debuginfo/debugsource package generation
%global debug_package %{nil}

Name:           libqrmi
Version:        %{version}
Release:        1%{?dist}
Summary:        Quantum Resource Management Interface (QRMI) dynamic library
License:        Apache-2.0
URL:            https://github.com/qiskit-community/qrmi
Source0:        qrmi-%{version}.tar.gz
Source1:        qrmi-vendor-%{version}.tar.gz

Provides:       libqrmi.so()(64bit)

BuildRequires:  gcc
BuildRequires:  gcc-c++
BuildRequires:  make
BuildRequires:  cmake
BuildRequires:  openssl-devel
BuildRequires:  zlib-devel
BuildRequires:  pkg-config

%description
This package contains the libqrmi.so and qrmi.h

# ---------------------------------------------------------------------------
# Prep
# ---------------------------------------------------------------------------
%prep
%autosetup -n qrmi-%{version}

# Unpack the vendored Rust dependencies
tar xf %{SOURCE1}

# Configure Cargo to use the vendored sources (offline build)
mkdir -p .cargo
cat > .cargo/config.toml << 'EOF'
[source.crates-io]
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"
EOF

# ---------------------------------------------------------------------------
# Build
# ---------------------------------------------------------------------------
%build
# Source the Rust environment if installed via rustup
[ -f "$HOME/.cargo/env" ] && . "$HOME/.cargo/env"

# Build the shared library
make build

# ---------------------------------------------------------------------------
# Install
# ---------------------------------------------------------------------------
%install
install -d %{buildroot}%{_libdir}
install -d %{buildroot}%{_includedir}

# Shared library
install -m 0755 target/release/libqrmi.so \
    %{buildroot}%{_libdir}/libqrmi.so.%{version}
ln -sf libqrmi.so.%{version} \
    %{buildroot}%{_libdir}/libqrmi.so.0
ln -sf libqrmi.so.0 \
    %{buildroot}%{_libdir}/libqrmi.so

# C header (generated by cbindgen during the cargo build)
install -m 0644 qrmi.h \
    %{buildroot}%{_includedir}/qrmi.h

# ---------------------------------------------------------------------------
# Post-install / post-uninstall ldconfig triggers
# ---------------------------------------------------------------------------
%post -p /sbin/ldconfig
%postun -p /sbin/ldconfig

# ---------------------------------------------------------------------------
# Files
# ---------------------------------------------------------------------------
%files
%license LICENSE.txt
%doc README.md INSTALL.md
%{_includedir}/qrmi.h
%{_libdir}/libqrmi.so.%{version}
%{_libdir}/libqrmi.so.0
%{_libdir}/libqrmi.so

# ---------------------------------------------------------------------------
# Changelog
# ---------------------------------------------------------------------------
%changelog
* %(date "+%a %b %d %Y") QRMI - %{version}-%{release}
- Auto generated changelog entry