# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import enum
import typing
__all__ = [
    "AuthenticationFailedError",
    "Config",
    "ConfigError",
    "EnvVarNotSetError",
    "InvalidInputError",
    "Payload",
    "QRMIService",
    "QrmiError_",
    "QuantumResource",
    "ResourceCapacity",
    "ResourceDef",
    "ResourceNotFoundError",
    "ResourceProvider",
    "ResourceStatus",
    "ResourceStatusCode",
    "ResourceType",
    "Target",
    "TaskNotFoundError",
    "TaskNotReadyError",
    "TaskResult",
    "TaskStatus",
    "UnsupportedFunctionError",
    "UnsupportedPayloadError",
    "UnsupportedResourceTypeError",
    "set_log_callback",
]

class AuthenticationFailedError(builtins.QrmiError_):
    r"""
    The request's credentials were missing or rejected by the vendor's API.
    """
    ...

@typing.final
class Config:
    r"""
    Python wrapper for QRMI configuration.
    
    # Example (Python)
    
    .. code-block:: python
    
        from qrmi import Config, ResourceProvider
    
        config = Config.load("/path/to/qrmi_config.json")
    
        # Iterate over all resource definitions
        for name, resource_def in config.resource_map.items():
            print(f"{name}: is_dynamic={resource_def.is_dynamic}")
            if resource_def.is_dynamic:
                provider = ResourceProvider(resource_def.resource_type, resource_def.environment)
                resources = provider.resources()
    """
    @property
    def resource_map(self) -> builtins.dict[builtins.str, ResourceDef]:
        r"""
        Returns a dict mapping resource name to ResourceDef.
        """
    @staticmethod
    def load(path: builtins.str) -> Config:
        r"""
        Loads a QRMI config file.
        """

class ConfigError(builtins.QrmiError_):
    r"""
    A configuration value was missing, could not be parsed, or was otherwise invalid (covers `QrmiError::ParseError`, `QrmiError::MissingConfigKey`, and `QrmiError::InvalidConfig`).
    """
    ...

class EnvVarNotSetError(builtins.QrmiError_):
    r"""
    A required environment variable was not set.
    """
    ...

class InvalidInputError(builtins.QrmiError_):
    r"""
    A value QRMI was given was invalid, whether QRMI itself rejected it \
    locally (e.g. a malformed `filters` string, JSON, or UTF-8) or a \
    vendor's API rejected the resulting request after receiving it.
    """
    ...

@typing.final
class QRMIService:
    r"""
    Python wrapper for `QRMIService`.
    
    Discovers the QPU resources assigned to the current job -- read from the
    `QRMI_JOB_QPU_RESOURCES` / `QRMI_JOB_QPU_TYPES` environment variables, or
    their legacy `SLURM_JOB_QPU_RESOURCES` / `SLURM_JOB_QPU_TYPES`
    equivalents -- and exposes the ones that are currently accessible as
    `QuantumResource` instances.
    
    This is a thin wrapper around the plain-Rust [`crate::QRMIService`],
    which does the actual discovery/filtering and is usable on its own from
    Rust (see its docs for a Rust example). This wrapper's job is only to
    bridge that to Python: it drives `QRMIService::new()`'s `Future` to
    completion on a private tokio `Runtime` (mirroring `PyResourceProvider`
    and `PyQuantumResource` elsewhere in this module, since `pyo3` classes
    can't themselves be `async`), then moves each resource returned by
    `QRMIService::into_resource_map()` into its own, independently owned
    `PyQuantumResource` -- exactly as `PyResourceProvider::resources()` does
    for each `Box<dyn QuantumResource>` returned by
    `ResourceProvider::resources()`.
    
    # Example (Python)
    
    .. code-block:: python
    
        from qrmi import QRMIService
    
        service = QRMIService()
        for resource in service.resources():
            print(resource.resource_id())
    
        resource = service.resource("ibm_torino")
    """
    def __new__(cls) -> QRMIService: ...
    def resources(self) -> builtins.list[QuantumResource]:
        r"""
        Returns all accessible QRMI resources.
        """
    def resource(self, resource_id: builtins.str) -> typing.Optional[QuantumResource]:
        r"""
        Returns a single resource matching the specified resource identifier.
        
        # Arguments
        
        * `resource_id` - A resource identifier, i.e. backend name for IBM Quantum.
        
        Returns `None` if not found.
        """

class QrmiError_(builtins.RuntimeError):
    r"""
    Base class for all QRMI-specific errors. Catching this catches any error QRMI itself raises (as opposed to errors surfaced verbatim from an underlying vendor library).
    """
    ...

@typing.final
class QuantumResource:
    def __new__(cls, resource_id: builtins.str, resource_type: ResourceType) -> QuantumResource: ...
    @staticmethod
    def from_config(resource_id: builtins.str, resource_type: ResourceType, config: typing.Mapping[builtins.str, builtins.str]) -> QuantumResource:
        r"""
        Constructs a `QuantumResource` from a config of type `dict[str, str]`
        """
    def is_accessible(self) -> builtins.bool: ...
    def status(self) -> ResourceStatus: ...
    def resource_id(self) -> builtins.str: ...
    def resource_type(self) -> ResourceType: ...
    def acquire(self) -> builtins.str: ...
    def release(self, id: builtins.str) -> None: ...
    def task_start(self, payload: Payload) -> builtins.str: ...
    def task_stop(self, task_id: builtins.str) -> None: ...
    def task_status(self, task_id: builtins.str) -> TaskStatus: ...
    def task_result(self, task_id: builtins.str) -> TaskResult: ...
    def task_logs(self, task_id: builtins.str) -> builtins.str: ...
    def target(self) -> Target: ...
    def describe(self) -> dict[str, typing.Any]:
        r"""
        Returns the configuration and attributes of this resource as a
        JSON-serializable dict. Replaces the deprecated ``metadata()``.
        """
    def metadata(self) -> builtins.dict[builtins.str, builtins.str]:
        r"""
        Deprecated: use ``describe()`` instead.
        """

@typing.final
class ResourceCapacity:
    r"""
    Resource capacity.
    """
    ...

@typing.final
class ResourceDef:
    r"""
    Python wrapper for a QRMI resource definition.
    """
    @property
    def name(self) -> builtins.str:
        r"""
        Resource name.
        """
    @property
    def resource_type(self) -> ResourceType:
        r"""
        Resource type.
        """
    @property
    def is_dynamic(self) -> builtins.bool:
        r"""
        Whether this resource definition is dynamic.
        """
    @property
    def environment(self) -> builtins.dict[builtins.str, builtins.str]:
        r"""
        Environment variables for this resource.
        """

class ResourceNotFoundError(builtins.QrmiError_):
    r"""
    The named resource (e.g. a backend) does not exist.
    """
    ...

@typing.final
class ResourceProvider:
    r"""
    Python wrapper for `ResourceProvider`.
    
    # Example (Python)
    
    .. code-block:: python
    
        from qrmi import Config, ResourceProvider, ResourceType
    
        config = Config.load("/path/to/qrmi_config.json")
        resource_def = config.resource_map["ibm_inst1"]
    
        provider = ResourceProvider(ResourceType.IBMQuantumComputeService, resource_def.environment)
        resources = provider.resources()
        resources = provider.resources("num_qubits=127&name=ibm_*&status=online")
        resource  = provider.least_busy()
    
        for r in resources:
            print(r.resource_id())
    """
    def __new__(cls, resource_type: ResourceType, environment: typing.Mapping[builtins.str, builtins.str]) -> ResourceProvider:
        r"""
        Constructs a new provider from a resource type and environment variable map.
        
        Currently supported resource types:
        - `ResourceType.IBMQiskitRuntimeService`(deprecated)
        - `ResourceType.IBMQuantumComputeService`
        - `ResourceType.IBMQuantumSystem`
        """
    def resources(self, filters: typing.Optional[builtins.str] = None) -> builtins.list[QuantumResource]:
        r"""
        Returns available quantum resources, optionally filtered.
        
        # Arguments
        
        * `filters` - Filter string of the form `key=value&key=value`, or `None`.
        
        Filter specifications (constraints) are defined by each resource provider's implementation.
        Results are expected to be sorted in least-busy order.
        
        # Example (Python)
        
        .. code-block:: python
        
            resources = provider.resources()
            resources = provider.resources("num_qubits=127&name=ibm_*")
        """
    def least_busy(self, filters: typing.Optional[builtins.str] = None) -> typing.Optional[QuantumResource]:
        r"""
        Returns the least busy available quantum resource, optionally filtered.
        
        Equivalent to `resources(filters)[0]` but returns `None` if no resources match.
        
        # Example (Python)
        
        .. code-block:: python
        
            resource = provider.least_busy()
            resource = provider.least_busy("num_qubits=127&status=online")
        """

@typing.final
class ResourceStatus:
    r"""
    cbindgen:ignore
    """
    def to_dict(self) -> typing.Any:
        r"""
        Returns this status as a plain, JSON-serializable dict.
        Equivalent to calling ``json.dumps(status.to_dict())``.
        
        Field values mirror this struct's ``serde::Serialize``
        implementation: ``status`` is a lowercase string (e.g.
        ``"online"``), and fields the vendor does not report
        (``status_reason``, ``healthy``, ``busy``, ``capacity``,
        ``pending_job_count``) are ``None``.
        """

@typing.final
class Target:
    r"""
    A Target that contains the constraints(supported instructions, properties etc.) of a particular quantum device
    """
    ...

class TaskNotFoundError(builtins.QrmiError_):
    r"""
    The named task (e.g. a job) does not exist, or has already been removed.
    """
    ...

class TaskNotReadyError(builtins.QrmiError_):
    r"""
    The task is not in a state that allows the requested operation (e.g. its result was requested while it is still running).
    """
    ...

@typing.final
class TaskResult:
    r"""
    Task result
    """
    ...

class UnsupportedFunctionError(builtins.QrmiError_):
    r"""
    The requested operation is not supported by this resource.
    """
    ...

class UnsupportedPayloadError(builtins.QrmiError_):
    r"""
    The payload (or a value within it, such as a program ID) is not supported by this backend.
    """
    ...

class UnsupportedResourceTypeError(builtins.QrmiError_):
    r"""
    Dynamic discovery was requested for an unsupported resource type.
    """
    ...

@typing.final
class Payload(enum.Enum):
    r"""
    Task Payload
    """
    QiskitPrimitive = ...
    r"""
    Payload that contains Qiskit Primitive input.
    """
    PasqalCloud = ...
    r"""
    Payload for Pasqal Cloud
    """
    AliceBobFelis = ...
    r"""
    Payload for Alice and Bob's Cloud API AKA. Felis
    """
    IQMServer = ...
    r"""
    Payload for IQM Server
    """
    Oqtopus = ...
    r"""
    Payload for OQTOPUS Cloud
    """

@typing.final
class ResourceStatusCode(enum.Enum):
    r"""
    Resource statuses.
    """
    Online = ...
    r"""
    Online and available.
    """
    Offline = ...
    r"""
    Offline and unavailable.
    """
    Paused = ...
    r"""
    Online but not currently accepting/running jobs due to a
    maintenance-type event (e.g. calibration),
    """

@typing.final
class ResourceType(enum.Enum):
    IBMQuantumSystem = ...
    IBMQiskitRuntimeService = ...
    IBMQuantumComputeService = ...
    PasqalCloud = ...
    PasqalLocal = ...
    AliceBobFelis = ...
    IQMServer = ...
    OQTOPUS = ...

@typing.final
class TaskStatus(enum.Enum):
    r"""
    Task statuses.
    """
    Queued = ...
    r"""
    Task is queued
    """
    Running = ...
    r"""
    Task is running
    """
    Completed = ...
    r"""
    Task was completed
    """
    Failed = ...
    r"""
    Task was failed
    """
    Cancelled = ...
    r"""
    Task was cancelled
    """

def set_log_callback(callback: typing.Optional[typing.Any]) -> None:
    r"""
    Registers a user-supplied Python callable as the destination for
    QRMI's `log` records, replacing whatever sink is currently active --
    including the default one installed at import time (see
    `python_log_sink` above). This is the Python-facing equivalent of the
    C API's `qrmi_log_callback_set`.
    
    `callback` is called as `callback(level, target, message)`, all three
    arguments `str`. `level` is one of `"ERROR"`, `"WARN"`, `"INFO"`,
    `"DEBUG"`, `"TRACE"`. Pass `None` to clear it, which reverts to plain
    stderr output -- the same fallback the C API's `NULL` reverts to --
    rather than back to the built-in `logging`-forwarding sink. Once you
    take over logging, where it goes (including back to `logging`, if
    that's what you want) is entirely your callback's responsibility.
    
    # Notes
    
    - `callback` may run on any thread, including a tokio worker thread
      unrelated to whichever Python thread called into QRMI. This is safe
      as long as every blocking QRMI call keeps releasing the GIL for its
      duration (see the `py.detach(...)` calls throughout this module) --
      that is what lets a worker thread acquire the GIL here without
      deadlocking against a QRMI call that is still holding it.
    - `callback` runs synchronously and holds the GIL while it runs; a slow
      callback delays whichever QRMI call happened to trigger the log
      record it's handling. Keep it fast -- e.g. hand off to a queue --
      if you need to do anything slow with a record.
    - If `callback` raises, the exception is printed (as an unhandled
      exception would be) and otherwise discarded; it cannot propagate
      back into the Rust code that logged in the first place.
    - Like `python_log_sink`, this uses `Python::try_attach`: if a record
      is emitted while the interpreter is finalizing, `callback` is simply
      not called for it rather than risking the same hang/segfault hazard
      `Python::attach` has in that window.
    """

