---
name: 'detect-secrets'
description: 'Scans your GitHub repository for accidentally committed secrets, enhances code security, and help cleanup the secrets'
  
# This is our CI enforcement method (Remediation, not the prevention) 
# secret commit is prevented using pre-commit methods as described in README.md
# This method detect/remediate any secrets mistakenly coming into our repo
on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      reason:
        description: 'Manual testing of this workflow'
        required: false
        default: 'Manual testing'
      
jobs:
  secret-detection:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      # Install detect-secrets. latest version is 1.5.0. 2026 April
      - name: Install detect secret pacakge
        run: |
          pip install "detect-secrets==1.5.0"
          # package for JSON operations.
          pip install jq

      # In case .secret.baseline file does not exist, code still has to run by 
      # generating empty baseline
      - name: Sanity check .secrets.baseline file
        run: |
          if [ ! -f .secrets.baseline ]; then
            echo "No.secrets.baseline detected. Creating a new blank baseline file."
            mkdir empty-dir
            detect-secrets scan empty-dir > .secrets.baseline
            echo "Blank .secrets.baseline file created successfully."
            rm -r empty-dir
          else
            echo ".secrets.baseline detected."
          fi

      # Scan entire repository for detecting secrets
      - name: Scan repository
        run: |
          # save the list of known secrets
          cp .secrets.baseline .secrets.new

          # find the secrets in the repository
          detect-secrets scan --force-use-all-plugins --exclude-files '.secrets.*' --exclude-files '.git*' --baseline .secrets.new     

          # Function to compare secrets without listing them
          compare_secrets() { diff <(jq -r '.results | keys[] as $key | "\($key),\(.[$key] | .[] | .hashed_secret)"' "$1" | sort) <(jq -r '.results | keys[] as $key | "\($key),\(.[$key] | .[] | .hashed_secret)"' "$2" | sort) >/dev/null; }
        
          # Check if there's any difference between the baseline and new detected secrets 
          if ! compare_secrets .secrets.baseline .secrets.new; then
            echo "New secrets have been detected in your recent commit. Due to security concerns, we cannot display detailed information here and we cannot proceed until this issue is resolved." >&2
            echo "" >&2
            echo "Run the 'detect-secrets scan' tool on your local machine. This tool will identify and clean up the secrets. You can find detailed instructions at this link: https://github.com/qiskit-community/qrmi/tree/main?tab=readme-ov-file#pre-commit-detect-secrets" >&2
            echo "" >&2
            echo "After cleaning up the secrets, commit your changes and re-push your update to the repository." >&2
            exit 1
          fi
