---
# This reusable workflow runs Python format check and lint on the QRMI wheels package.
#
# Workflow inputs:
# - [required] python-version
#
# Workflow artifacts produced:
# - None
#
# Workflow dependencies:
# - It downloads the qrmi-wheels artifact (uploaded by another workflow)
name: Lint and format check Python code
on:
  workflow_call:
    inputs:
      python-version:
        description: >-
          Python version to be used to lint the code
        type: string
        required: true
jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Install package dependencies from distro
      run: xargs dnf install -y < requirements-distro.txt

    - name: Download QRMI wheels
      uses: actions/download-artifact@v6
      with:
        name: qrmi-wheels

    - name: Setup Rust toolchain
      uses: actions-rust-lang/setup-rust-toolchain@v1

    # The python3.12 installed using actions/setup-python@v6,
    # requires a glibc version that is not available in the UBI container image
    - name: Install python ${{ inputs.python-version }} from distro
      run: dnf install -y python${{ inputs.python-version }}{,-pip}

    - name: Create and activate venv for subsequent steps
      run: |
        python${{ inputs.python-version }} -m venv .venv
        echo "${GITHUB_WORKSPACE}/.venv/bin" >> ${GITHUB_PATH}

    - name: Install python requirements
      run: pip install -r requirements-dev.txt

    - name: Install QRMI wheels
      run: pip install qrmi-*.whl

    - name: Format check with black
      run: black --check ./python

    - name: Lint with pylint
      run: pylint ./python
