---
# Workflow that runs on pull requests

name: Pull request

on:
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ${{ github.repository }}-${{ github.ref }}-${{ github.head_ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:

  libqrmi:
    if: github.repository_owner == 'qiskit-community'
    uses: ./.github/workflows/build-libqrmi.yml
    with:
      arch-x86_64: true
      build-target: 'all'
      unit-test-target: 'all'
      lint-target: 'all'
      format-check: true

  wheels:
    if: github.repository_owner == 'qiskit-community'
    uses: ./.github/workflows/build-wheels.yml
    with:
      arch-x86_64: true
      unit-test: true
      format-check: true
      lint: true
