---
# Workflow that runs on pull requests

name: Pull request

on:
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ${{ github.repository }}-${{ github.ref }}-${{ github.head_ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:

  # Only x86_64 is selected for libqrmi in this worflow. The other architectures are handled in the on-schedule workflow.
  # Build, unit-test, lint and format-check all QRMI Rust targets (including libqrmi)
  libqrmi:
    if: github.repository_owner == 'qiskit-community'
    uses: ./.github/workflows/libqrmi.yml
    with:
      arch-x86_64: true
      build-target: 'all'
      unit-test-target: 'all'
      lint-target: 'all'
      format-check: true
      artifact-prefix: 'pr-${{ github.event.number }}'

  # Only x86_64 is selected for wheels in this workflow. The other architectures are handled in the on-schedule workflow.
  # Build, unit-test, lint and format check wheels.
  wheels:
    if: github.repository_owner == 'qiskit-community'
    uses: ./.github/workflows/wheels.yml
    with:
      arch-x86_64: true
      unit-test: true
      format-check: true
      lint: true
      artifact-prefix: 'pr-${{ github.event.number }}'
