---
# SPDX-License-Identifier: Apache-2.0
# (C) Copyright IBM Corporation 2026

# This workflow creates a new QRMI release.
#
# Requires:
# - GITHUB_TOKEN secret
#
# Release assets:
# - qrmi-{version}-vendor.tar.gz
# - libqrmi-{version}-el8-x86_64.tar.gz

name: Release
on:
  workflow_dispatch:
  
jobs:

  # Check if the current QRMI version has already been released.
  # It also provides the checked QRMI version to other jobs through
  # the needs field.
  valid-qrmi-version:
    if: github.repository_owner == 'qiskit-community'
    name: Check new QRMI version is valid
    runs-on: ubuntu-24.04
    outputs:
      version: ${{ steps.qrmi-info.outputs.version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      # Ubuntu runner already comes with the package make installed

      - name: Check the new QRMI version is valid
        run: make check-new-qrmi-version-valid

      - name: Get QRMI information
        id: qrmi-info
        run: |
          QRMI_VERSION=$(make get-qrmi-version)
          echo "version=$QRMI_VERSION" >> $GITHUB_OUTPUT
          echo "QRMI version: $QRMI_VERSION"

  create-vendor-tarball:
    if: github.repository_owner == 'qiskit-community'
    name: Create vendor tarball
    needs: [valid-qrmi-version]
    uses: ./.github/workflows/tarball-vendor.yml

  create-libqrmi-tarball-rhel:
    if: github.repository_owner == 'qiskit-community'
    name: Create libqrmi tarball for RHEL compatible distributions
    needs: [valid-qrmi-version]
    uses: ./.github/workflows/tarball-libqrmi-el8.yml
      
  create-draft-release:
    if: github.repository_owner == 'qiskit-community'
    name: Create draft release and populate it with assets
    needs: [valid-qrmi-version, create-vendor-tarball, create-libqrmi-tarball-rhel]
    permissions:
      contents: write # required to create a draft release
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Create draft release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create --draft --generate-notes --title "QRMI v${{ needs.valid-qrmi-version.outputs.version }}" "v${{ needs.valid-qrmi-version.outputs.version }}"
  
      - name: Download vendor tarball
        uses: actions/download-artifact@v8
        with:
          name: qrmi-vendor-tarball

      - name: Upload vendor tarball
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload "v${{ needs.valid-qrmi-version.outputs.version }}" qrmi-${{ needs.valid-qrmi-version.outputs.version }}-vendor.tar.gz --clobber

      - name: Download libqrmi tarball for RHEL compatible distributions
        uses: actions/download-artifact@v8
        with:
          name: libqrmi-${{ needs.valid-qrmi-version.outputs.version }}-el8-x86_64-tarball

      - name: Upload libqrmi tarball for RHEL compatible distributions
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload "v${{ needs.valid-qrmi-version.outputs.version }}" libqrmi-${{ needs.valid-qrmi-version.outputs.version }}-el8-x86_64.tar.gz --clobber
    
  publish-github:
    if: github.repository_owner == 'qiskit-community'
    name: Publish github release
    needs: [valid-qrmi-version, create-draft-release]
    permissions:
      contents: write # This is required to publish the draft release
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v6

    - name: Publish release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Make the release live on github
        gh release edit "v${{ needs.valid-qrmi-version.outputs.version }}" --verify-tag --draft=false

  build-and-test-wheels:
    if: github.repository_owner == 'qiskit-community'
    needs: [valid-qrmi-version]
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-24.04
          - ubuntu-24.04-arm
          - ubuntu-24.04-ppc64le
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-python@v6
      with:
        python-version: 3.12
    - name: Build QRMI wheels
      uses: pypa/cibuildwheel@v3.4.1
      env:
        CIBW_TEST_EXTRAS: all
    - name: Upload QRMI wheels
      uses: actions/upload-artifact@v7
      if: ${{ success() }}
      with:
        name: release-wheels-${{ matrix.os }}
        path: ./wheelhouse/*.whl
        if-no-files-found: error
        retention-days: 1

  wheels-sdist:
    if: github.repository_owner == 'qiskit-community'
    needs: [valid-qrmi-version]
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v6
    - name: Build sdist
      uses: PyO3/maturin-action@v1
      with:
        target: x86_64
        manylinux: 2_28
        command: sdist
        args: --out dist
    - name: Upload QRMI sdist
      uses: actions/upload-artifact@v7
      if: ${{ success() }}
      with:
        name: release-wheels-sdist
        path: dist/*.tar.gz
        if-no-files-found: error
        retention-days: 1

  publish-pypi:
    if: github.repository_owner == 'qiskit-community'
    needs: [build-and-test-wheels, wheels-sdist, publish-github]
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/project/qrmi
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
    - uses: actions/download-artifact@v8
      with:
        pattern: release-wheels-*
        merge-multiple: true
        path: dist/
    - name: Publish QRMI wheels
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        verbose: true
        print-hash: true

  # Once a package version is released to either pypi.org or test.pypi.org,
  # it cannot be overwritten or deleted/reused. This job checks if the
  # version released to pypi can be installed and downloaded correctly.
  # That could help to catch and address issues early.
  check-pypi-post-release:
    if: github.repository_owner == 'qiskit-community'
    needs: [publish-pypi, valid-qrmi-version]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v6
      with:
        python-version: 3.12
    - name: Check published wheel
      run: |
        python3.12 -m venv .venv_py312
        source .venv_py312/bin/activate
        pip install --upgrade pip
        pip install qrmi==${{ needs.valid-qrmi-version.outputs.version }}
        pip download qrmi==${{ needs.valid-qrmi-version.outputs.version }} --no-binary qrmi --no-deps
