---
# SPDX-License-Identifier: Apache-2.0
# (C) Copyright IBM Corporation 2026

# Workflow that creates and publishes a new QRMI release in github and pypi.

# ATTENTION:
# If you change the name of this workflow filename, please make
# sure to also update the Trusted Publisher configuration in 
# the PyPI qrmi account.

name: Release
on:
  workflow_dispatch:
  
jobs:

  # Check if the current QRMI version has already been released.
  # It also provides the checked QRMI version to other jobs through
  # the needs field.
  qrmi-info:
    if: github.repository_owner == 'qiskit-community'
    runs-on: ubuntu-24.04
    outputs:
      valid-qrmi-version: ${{ steps.info.outputs.qrmi-version }}
      python-version: ${{ steps.info.outputs.python-version }}
    steps:
      - uses: actions/checkout@v6
      - run: make check-new-qrmi-version-valid
      - name: Information
        id: info
        run: |
          echo "qrmi-version=$(make get-qrmi-version)" >> $GITHUB_OUTPUT
          echo "python-version=$(make get-python-version)" >> $GITHUB_OUTPUT

  # Build and test the libqrmi tarball for x86_64.
  # Create the vendor source tarball
  libqrmi-x86_64:
    if: github.repository_owner == 'qiskit-community'
    needs: [qrmi-info]
    uses: ./.github/workflows/libqrmi.yml
    with:
      arch-x86_64: true
      build-target: 'libqrmi-only'
      unit-test-target: 'libqrmi-only'
      libqrmi-tarball: true
      vendor-tarball: true
      artifact-prefix: 'release'

  # Build the libqrmi tarball for non-x86_64 architectures.
  # No other task is performed (e.g. test or lint) as they can significantly increase the total time.
  libqrmi-other-archs:
    if: github.repository_owner == 'qiskit-community'
    needs: [qrmi-info]
    uses: ./.github/workflows/libqrmi.yml
    with:
      arch-x86_64: false
      arch-ppc64le: true
      arch-arm64: true
      build-target: 'libqrmi-only'
      libqrmi-tarball: true
      artifact-prefix: 'release'

  publish-github:
    if: github.repository_owner == 'qiskit-community'
    name: Create draft release with artifacts and publish it
    needs: [qrmi-info, libqrmi-x86_64, libqrmi-other-archs]
    permissions:
      contents: write # required to create a draft release
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - name: Create draft release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release create --draft --generate-notes --title "QRMI ${{ needs.qrmi-info.outputs.valid-qrmi-version }}" "${{ needs.qrmi-info.outputs.valid-qrmi-version }}"
      - name: Download vendor tarball
        uses: actions/download-artifact@v8
        with:
          name: release-qrmi-${{ needs.qrmi-info.outputs.valid-qrmi-version }}-vendor-tarball
          path: dist/
      - name: Download libqrmi tarball built for all archs
        uses: actions/download-artifact@v8
        with:
          pattern: release-libqrmi-${{ needs.qrmi-info.outputs.valid-qrmi-version }}-tarball-*
          merge-multiple: true
          path: dist/
      - name: Upload artifacts found in the dist directory
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload "${{ needs.qrmi-info.outputs.valid-qrmi-version }}" dist/* --clobber
      - name: Publish release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release edit "${{ needs.qrmi-info.outputs.valid-qrmi-version }}" --verify-tag --draft=false

  # Build and test the wheels for x86_64
  # Create qrmi source distribution for PyPI
  wheels-x86_64:
    if: github.repository_owner == 'qiskit-community'
    needs: [qrmi-info]
    uses: ./.github/workflows/wheels.yml
    with:
      arch-x86_64: true
      unit-test: true
      sdist: true
      artifact-prefix: 'release'

  # Build the wheels for non-x86_64
  # No other task is performed (e.g. test or lint) as they can increases the total time to around 4 hours
  wheels-other-archs:
    if: github.repository_owner == 'qiskit-community'
    needs: [qrmi-info]
    uses: ./.github/workflows/wheels.yml
    with:
      arch-x86_64: false
      arch-ppc64le: true
      arch-arm64: true
      artifact-prefix: 'release'

  publish-pypi:
    if: github.repository_owner == 'qiskit-community'
    needs: [wheels-x86_64, wheels-other-archs, publish-github, qrmi-info]
    runs-on: ubuntu-24.04
    # ATTENTION:
    # If you change the pypi variable name below, please make sure to also update the
    # Trusted Publisher configuration in the PyPI qrmi account.
    environment:
      name: pypi
      url: https://pypi.org/project/qrmi
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
    - name: Download the wheels built for all archs
      uses: actions/download-artifact@v8
      with:
        pattern: release-qrmi-${{ needs.qrmi-info.outputs.valid-qrmi-version }}-wheels-*
        merge-multiple: true
        path: dist/
    - name: Download sdist built
      uses: actions/download-artifact@v8
      with:
        name: release-qrmi-${{ needs.qrmi-info.outputs.valid-qrmi-version }}-pypi-sdist
        path: dist/
    - name: Publish QRMI wheels
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        verbose: true
        print-hash: true

  # Once a package version is released to either pypi.org or test.pypi.org,
  # it cannot be overwritten or deleted/reused. This job checks if the
  # version released to pypi can be installed and downloaded correctly.
  # That could help to catch and address issues early.
  check-pypi-post-release:
    if: github.repository_owner == 'qiskit-community'
    needs: [publish-pypi, qrmi-info]
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/setup-python@v6
      with:
        python-version: ${{ needs.qrmi-info.outputs.python-version }}
    - name: Check published wheel
      run: |
        python${{ needs.qrmi-info.outputs.python-version }} -m venv .venv
        source .venv/bin/activate
        pip install --upgrade pip
        pip install qrmi==${{ needs.qrmi-info.outputs.valid-qrmi-version }}
        pip download qrmi==${{ needs.qrmi-info.outputs.valid-qrmi-version }} --no-binary qrmi --no-deps
