---
# workflow that runs a major set of tests on a defined schedule 

name: Unit Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - run: pip install -e .[dev]

      - run: pip install pytest-cov

      - name: Run unit tests
        run: |
          pytest \
            --cov=qrmi \
            --cov-report=term-missing \
            --cov-report=xml \
##          --cov-fail-under=85