---
# This reusable workflow runs Rust unittests on the libqrmi, binaries and dependencies.
#
# Workflow inputs:
# - None
#
# Workflow artifacts produced:
# - None
#
# Workflow dependencies:
# - None. It does not depend on any other workflow.
name: Unittest QRMI Rust code
on:
  workflow_call:
env:
  CARGO_TERM_COLOR: always
jobs:
  unittest:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Setup Rust toolchain
      uses: actions-rust-lang/setup-rust-toolchain@v1

    - name: Unittest libqrmi.so (includes examples)
      run: make test-libqrmi

    - name: Unittest binaries
      run: make test-bins

    - name: Unittest dependencies
      run: make test-dependencies
